#!/bin/bash
# Plays Riptide on macOS: brings the game's code up to date (quick when nothing has changed), then starts the game in
# its own window. Double-click it in Finder. Set UE_ROOT if Unreal Engine 5.7 isn't in the default place.
UE_ROOT="${UE_ROOT:-/Users/Shared/Epic Games/UE_5.7}"
PROJECT="$(cd "$(dirname "$0")/../.." && pwd)/Riptide.uproject"

echo "Getting Riptide ready..."
if ! "$UE_ROOT/Engine/Build/BatchFiles/Mac/Build.sh" RiptideEditor Mac Development "-Project=$PROJECT" -WaitMutex > /tmp/riptide_build.log 2>&1; then
    echo
    echo "Riptide's code didn't build. The end of the build log:"
    tail -n 25 /tmp/riptide_build.log
    read -r -p "Press Return to close."
    exit 1
fi
# The game's maps, boat, crew, islands and items are generated by the editor, not kept in git: after an install or an
# update (a new commit) the editor runs once, hidden, to build them. Quick when nothing changed.
ROOT="$(dirname "$PROJECT")"
STAMP="$ROOT/Saved/riptide_content_stamp.txt"
HEAD="$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
if [ "$HEAD" != "$(cat "$STAMP" 2>/dev/null)" ]; then
    echo "Preparing the game's content. The first time, or after an update, this takes a few minutes..."
    "$UE_ROOT/Engine/Binaries/Mac/UnrealEditor.app/Contents/MacOS/UnrealEditor" "$PROJECT" -RenderOffscreen -unattended -nosplash -nosound -ExecCmds="QUIT_EDITOR"
    mkdir -p "$ROOT/Saved"
    echo "$HEAD" > "$STAMP"
fi
open -n "$UE_ROOT/Engine/Binaries/Mac/UnrealEditor.app" --args "$PROJECT" -game
