@echo off
rem Plays Riptide on Windows: brings the game's code up to date (quick when nothing has changed), then starts the
rem game in its own window. Set UE_ROOT if Unreal Engine 5.7 isn't in the default place.
setlocal
if "%UE_ROOT%"=="" set "UE_ROOT=C:\Program Files\Epic Games\UE_5.7"
set "PROJECT=%~dp0..\..\Riptide.uproject"
for %%I in ("%PROJECT%") do set "PROJECT=%%~fI"

echo Getting Riptide ready...
call "%UE_ROOT%\Engine\Build\BatchFiles\Build.bat" RiptideEditor Win64 Development "-Project=%PROJECT%" -WaitMutex -NoHotReload > "%TEMP%\riptide_build.log" 2>&1
if errorlevel 1 (
    echo.
    echo Riptide's code didn't build. The end of the build log:
    powershell -NoProfile -Command "Get-Content '%TEMP%\riptide_build.log' -Tail 25"
    echo.
    pause
    exit /b 1
)
rem The game's maps, boat, crew, islands and items are generated by the editor, not kept in git: after an install or
rem an update (a new commit) the editor runs once, hidden, to build them. Quick when nothing changed.
set "ROOT=%~dp0..\.."
set "STAMP=%ROOT%\Saved\riptide_content_stamp.txt"
set "HEAD=unknown"
for /f %%H in ('git -C "%ROOT%" rev-parse HEAD 2^>nul') do set "HEAD=%%H"
set "DONE="
if exist "%STAMP%" set /p DONE=<"%STAMP%"
if not "%HEAD%"=="%DONE%" (
    echo Preparing the game's content. The first time, or after an update, this takes a few minutes...
    start "" /wait "%UE_ROOT%\Engine\Binaries\Win64\UnrealEditor.exe" "%PROJECT%" -RenderOffscreen -unattended -nosplash -nosound -ExecCmds="QUIT_EDITOR"
    if not exist "%ROOT%\Saved" mkdir "%ROOT%\Saved"
    > "%STAMP%" echo %HEAD%
)
start "" "%UE_ROOT%\Engine\Binaries\Win64\UnrealEditor.exe" "%PROJECT%" -game
