#include "RiptideVoice.h"

#include "Components/AudioComponent.h"
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"
#include "Engine/Engine.h"
#include "Engine/LocalPlayer.h"
#include "EngineUtils.h"
#include "GameFramework/GameStateBase.h"
#include "GameFramework/PlayerController.h"
#include "GameFramework/PlayerState.h"
#include "InputAction.h"
#include "InputMappingContext.h"
#include "Kismet/GameplayStatics.h"
#include "TimerManager.h"
#include "RiptideBoat.h"
#include "RiptideCharacter.h"
#include "RiptidePlayerController.h"
#include "Sound/SoundAttenuation.h"
#include "Sound/SoundEffectSource.h"
#include "SourceEffects/SourceEffectFilter.h"
#include "SourceEffects/SourceEffectFoldbackDistortion.h"

namespace
{
	/** How far a voice carries: spoken, through a boat's radio speaker, and over a loudhailer (cm). */
	constexpr float VoiceInnerCm = 300.f;
	constexpr float VoiceFalloffCm = 2200.f;
	constexpr float RadioInnerCm = 150.f;
	constexpr float RadioFalloffCm = 900.f;
	constexpr float HailerInnerCm = 1500.f;
	constexpr float HailerFalloffCm = 13500.f;
	/** How long a heard radio line stays on screen. */
	constexpr double LineSeconds = 6.0;
	/** Above the crew's and the helm's controls, below the dev keys. */
	constexpr int32 VoiceInputPriority = 50;
}

// --- One remote voice ---

void URiptideVoiceTalker::OnTalkingBegin(UAudioComponent* AudioComponent)
{
	bTalking = true;
	if (Route == ERiptideVoiceRoute::Radio && Speaker.IsValid() && SquelchOpen)
	{
		UGameplayStatics::PlaySoundAtLocation(this, SquelchOpen, Speaker->GetComponentLocation());
	}
	Super::OnTalkingBegin(AudioComponent);
}

void URiptideVoiceTalker::OnTalkingEnd()
{
	bTalking = false;
	if (Route == ERiptideVoiceRoute::Radio && Speaker.IsValid() && SquelchClose)
	{
		UGameplayStatics::PlaySoundAtLocation(this, SquelchClose, Speaker->GetComponentLocation());
	}
	Super::OnTalkingEnd();
}

// --- The player's voice and radio ---

URiptideVoiceComponent::URiptideVoiceComponent()
{
	PrimaryComponentTick.bCanEverTick = true;
}

void URiptideVoiceComponent::BeginPlay()
{
	Super::BeginPlay();
	const APlayerController* PC = Cast<APlayerController>(GetOwner());
	if (!PC || !PC->IsLocalController())
	{
		SetComponentTickEnabled(false);
		return;
	}
	BuildAudio();
}

void URiptideVoiceComponent::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	SetPushToTalk(false);
	for (auto& Pair : Talkers)
	{
		if (IsValid(Pair.Value))
		{
			Pair.Value->DestroyComponent();
		}
	}
	Talkers.Reset();
	Super::EndPlay(EndPlayReason);
}

void URiptideVoiceComponent::BuildAudio()
{
	auto MakeFalloff = [this](float Inner, float Falloff)
	{
		USoundAttenuation* A = NewObject<USoundAttenuation>(this);
		A->Attenuation.bAttenuate = true;
		A->Attenuation.bSpatialize = true;
		A->Attenuation.AttenuationShape = EAttenuationShape::Sphere;
		A->Attenuation.AttenuationShapeExtents = FVector(Inner, 0.f, 0.f);
		A->Attenuation.FalloffDistance = Falloff;
		A->Attenuation.DistanceAlgorithm = EAttenuationDistanceModel::NaturalSound;
		return A;
	};
	VoiceFalloff = MakeFalloff(VoiceInnerCm, VoiceFalloffCm);
	RadioFalloff = MakeFalloff(RadioInnerCm, RadioFalloffCm);
	HailerFalloff = MakeFalloff(HailerInnerCm, HailerFalloffCm);

	// A small speaker's voice: the band a radio passes (lows and highs gone), driven a little into distortion. The
	// loudhailer is the same idea, wider and harder driven.
	auto MakeChain = [this](float CentreHz, float Q, float DriveDb, float ThresholdDb)
	{
		USourceEffectFilterPreset* Filter = NewObject<USourceEffectFilterPreset>(this);
		FSourceEffectFilterSettings FilterSettings;
		FilterSettings.FilterType = ESourceEffectFilterType::BandPass;
		FilterSettings.CutoffFrequency = CentreHz;
		FilterSettings.FilterQ = Q;
		Filter->SetSettings(FilterSettings);
		USourceEffectFoldbackDistortionPreset* Drive = NewObject<USourceEffectFoldbackDistortionPreset>(this);
		FSourceEffectFoldbackDistortionSettings DriveSettings;
		DriveSettings.InputGainDb = DriveDb;
		DriveSettings.ThresholdDb = ThresholdDb;
		DriveSettings.OutputGainDb = -DriveDb * 0.5f;
		Drive->SetSettings(DriveSettings);
		USoundEffectSourcePresetChain* Chain = NewObject<USoundEffectSourcePresetChain>(this);
		for (USoundEffectSourcePreset* Preset : { static_cast<USoundEffectSourcePreset*>(Filter), static_cast<USoundEffectSourcePreset*>(Drive) })
		{
			FSourceEffectChainEntry Entry;
			Entry.Preset = Preset;
			Entry.bBypass = false;
			Chain->Chain.Add(Entry);
		}
		return Chain;
	};
	RadioEffects = MakeChain(1700.f, 1.3f, 9.f, -14.f);
	HailerEffects = MakeChain(1500.f, 0.8f, 12.f, -10.f);

	// Generated by init_unreal.py (make_radio_sounds): the click and hiss of a radio opening and closing its squelch.
	SquelchOpen = LoadObject<USoundBase>(nullptr, TEXT("/Game/Riptide/Audio/S_RadioSquelchOpen.S_RadioSquelchOpen"));
	SquelchClose = LoadObject<USoundBase>(nullptr, TEXT("/Game/Riptide/Audio/S_RadioSquelchClose.S_RadioSquelchClose"));
}

void URiptideVoiceComponent::BuildInput()
{
	APlayerController* PC = Cast<APlayerController>(GetOwner());
	UEnhancedInputComponent* Input = PC ? Cast<UEnhancedInputComponent>(PC->InputComponent) : nullptr;
	UEnhancedInputLocalPlayerSubsystem* Subsystem = PC ? ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PC->GetLocalPlayer()) : nullptr;
	if (!Input || !Subsystem || VoiceMapping)
	{
		return;
	}
	VoiceMapping = NewObject<UInputMappingContext>(this, TEXT("IMC_Voice"));
	auto Make = [this](const TCHAR* Name, std::initializer_list<FKey> Keys)
	{
		UInputAction* IA = NewObject<UInputAction>(this, Name);
		IA->ValueType = EInputActionValueType::Boolean;
		Actions.Add(IA);
		for (const FKey& Key : Keys)
		{
			VoiceMapping->MapKey(IA, Key);
		}
		return IA;
	};
	UInputAction* Talk = Make(TEXT("IA_PushToTalk"), { EKeys::V, EKeys::Gamepad_LeftThumbstick });
	UInputAction* ChannelDown = Make(TEXT("IA_RadioChannelDown"), { EKeys::LeftBracket });
	UInputAction* ChannelUp = Make(TEXT("IA_RadioChannelUp"), { EKeys::RightBracket });
	UInputAction* Mode = Make(TEXT("IA_MicMode"), { EKeys::B });
	Input->BindActionValueLambda(Talk, ETriggerEvent::Started, [this](const FInputActionValue&) { SetPushToTalk(true); });
	Input->BindActionValueLambda(Talk, ETriggerEvent::Completed, [this](const FInputActionValue&) { SetPushToTalk(false); });
	Input->BindActionValueLambda(ChannelDown, ETriggerEvent::Started, [this](const FInputActionValue&) { ChangeChannel(-1); });
	Input->BindActionValueLambda(ChannelUp, ETriggerEvent::Started, [this](const FInputActionValue&) { ChangeChannel(1); });
	Input->BindActionValueLambda(Mode, ETriggerEvent::Started, [this](const FInputActionValue&) { ToggleMicMode(); });
	Subsystem->AddMappingContext(VoiceMapping, VoiceInputPriority);
}

void URiptideVoiceComponent::SetPushToTalk(bool bDown)
{
	APlayerController* PC = Cast<APlayerController>(GetOwner());
	if (!PC || bDown == bPushToTalk)
	{
		return;
	}
	bPushToTalk = bDown;
	if (bDown)
	{
		PC->StartTalking();
	}
	else
	{
		PC->StopTalking();
	}
}

ARiptideBoat* URiptideVoiceComponent::RadioInReach() const
{
	const APlayerController* PC = Cast<APlayerController>(GetOwner());
	const ARiptideCharacter* Crew = PC ? CrewOf(PC->PlayerState) : nullptr;
	ARiptideBoat* Boat = Crew ? Crew->GetHomeBoat() : nullptr;
	return Boat && (Boat->GetMicHolder() == Crew || Boat->GetHelmsman() == Crew) ? Boat : nullptr;
}

void URiptideVoiceComponent::ChangeChannel(int32 Delta)
{
	if (ARiptideBoat* Boat = RadioInReach())
	{
		// Round the dial: past 40 back to 1.
		const int32 Channel = (Boat->GetRadioChannel() - 1 + Delta + MaxChannel * 4) % MaxChannel + 1;
		RequestRadio(Boat, Channel, Boat->GetMicMode());
	}
}

void URiptideVoiceComponent::ToggleMicMode()
{
	ARiptideBoat* Boat = RadioInReach();
	const APlayerController* PC = Cast<APlayerController>(GetOwner());
	if (Boat && PC && Boat->GetMicHolder() == CrewOf(PC->PlayerState))
	{
		RequestRadio(Boat, Boat->GetRadioChannel(),
			Boat->GetMicMode() == ERiptideMicMode::Radio ? ERiptideMicMode::Loudhailer : ERiptideMicMode::Radio);
	}
}

void URiptideVoiceComponent::RequestRadio(ARiptideBoat* Boat, int32 Channel, ERiptideMicMode Mode)
{
	if (ARiptidePlayerController* PC = Cast<ARiptidePlayerController>(GetOwner()))
	{
		PC->ServerSetRadio(Boat, Channel, Mode);
	}
}

void URiptideVoiceComponent::SetRadioFor(const APlayerController* PC, ARiptideBoat* Boat, int32 Channel, ERiptideMicMode Mode)
{
	// Only someone at the radio can work it: holding its mic, or at the helm beside it.
	const ARiptideCharacter* Crew = PC ? CrewOf(PC->PlayerState) : nullptr;
	if (IsValid(Boat) && Crew && (Boat->GetMicHolder() == Crew || Boat->GetHelmsman() == Crew))
	{
		Boat->SetRadio(Channel, Mode);
	}
}

ARiptideCharacter* URiptideVoiceComponent::CrewOf(const APlayerState* Player)
{
	if (!Player)
	{
		return nullptr;
	}
	APawn* Pawn = Player->GetPawn();
	if (ARiptideCharacter* Crew = Cast<ARiptideCharacter>(Pawn))
	{
		return Crew;
	}
	// Driving the boat: the crew member at its helm.
	const ARiptideBoat* Boat = Cast<ARiptideBoat>(Pawn);
	return Boat ? Boat->GetHelmsman() : nullptr;
}

ERiptideVoiceRoute URiptideVoiceComponent::RouteFor(const APlayerState* Talker, const APlayerController* Listener)
{
	const ARiptideCharacter* Crew = CrewOf(Talker);
	const ARiptideBoat* Boat = Crew ? Crew->GetHomeBoat() : nullptr;
	if (!Boat || Boat->GetMicHolder() != Crew)
	{
		return ERiptideVoiceRoute::Proximity;
	}
	if (Boat->GetMicMode() == ERiptideMicMode::Loudhailer)
	{
		return ERiptideVoiceRoute::Loudhailer;
	}
	// On the CB: heard over the radio of another boat on the same channel. Aboard the same boat you hear them
	// speaking into the mic (a radio doesn't play its own transmission), as you do on a boat tuned elsewhere.
	const ARiptideCharacter* ListenerCrew = Listener ? CrewOf(Listener->PlayerState) : nullptr;
	const ARiptideBoat* ListenerBoat = ListenerCrew ? ListenerCrew->GetHomeBoat() : nullptr;
	return ListenerBoat && ListenerBoat != Boat && ListenerBoat->GetRadioChannel() == Boat->GetRadioChannel()
		? ERiptideVoiceRoute::Radio : ERiptideVoiceRoute::Proximity;
}

void URiptideVoiceComponent::UpdateTalkers()
{
	const APlayerController* PC = Cast<APlayerController>(GetOwner());
	const AGameStateBase* GameState = GetWorld() ? GetWorld()->GetGameState() : nullptr;
	if (!PC || !GameState)
	{
		return;
	}
	// Forget players who have left.
	for (auto It = Talkers.CreateIterator(); It; ++It)
	{
		if (!IsValid(It.Key()) || !GameState->PlayerArray.Contains(It.Key()))
		{
			if (IsValid(It.Value()))
			{
				It.Value()->DestroyComponent();
			}
			It.RemoveCurrent();
		}
	}
	const ARiptideCharacter* ListenerCrew = CrewOf(PC->PlayerState);
	ARiptideBoat* ListenerBoat = ListenerCrew ? ListenerCrew->GetHomeBoat() : nullptr;
	for (APlayerState* Player : GameState->PlayerArray)
	{
		if (!IsValid(Player) || Player == PC->PlayerState || !Player->GetUniqueId().IsValid())
		{
			continue;
		}
		TObjectPtr<URiptideVoiceTalker>& Talker = Talkers.FindOrAdd(Player);
		if (!IsValid(Talker))
		{
			Talker = NewObject<URiptideVoiceTalker>(Player);
			Talker->RegisterComponent();
			Talker->RegisterWithPlayerState(Player);
			Talker->SquelchOpen = SquelchOpen;
			Talker->SquelchClose = SquelchClose;
		}
		// Where this voice comes out, applied as each transmission starts (the engine reads it then).
		const ERiptideVoiceRoute Route = RouteFor(Player, PC);
		const ARiptideCharacter* Crew = CrewOf(Player);
		const ARiptideBoat* Boat = Crew ? Crew->GetHomeBoat() : nullptr;
		FVoiceSettings& Settings = Talker->Settings;
		Talker->Route = Route;
		Talker->Speaker = nullptr;
		switch (Route)
		{
		case ERiptideVoiceRoute::Radio:
			Settings.ComponentToAttachTo = ListenerBoat ? ListenerBoat->GetRadioSpeaker() : nullptr;
			Settings.AttenuationSettings = RadioFalloff;
			Settings.SourceEffectChain = RadioEffects;
			Talker->Speaker = Settings.ComponentToAttachTo;
			break;
		case ERiptideVoiceRoute::Loudhailer:
			Settings.ComponentToAttachTo = Boat ? Boat->GetLoudhailerHorn() : nullptr;
			Settings.AttenuationSettings = HailerFalloff;
			Settings.SourceEffectChain = HailerEffects;
			break;
		default:
			Settings.ComponentToAttachTo = Crew ? Crew->GetRootComponent() : (Player->GetPawn() ? Player->GetPawn()->GetRootComponent() : nullptr);
			Settings.AttenuationSettings = VoiceFalloff;
			Settings.SourceEffectChain = nullptr;
			break;
		}
	}
}

void URiptideVoiceComponent::HearRadioLine(int32 Channel, ARiptideBoat* FromBoat, const FString& Speaker, const FString& Line, bool bLoudhailer)
{
	const APlayerController* PC = Cast<APlayerController>(GetOwner());
	const ARiptideCharacter* Crew = PC ? CrewOf(PC->PlayerState) : nullptr;
	ARiptideBoat* MyBoat = Crew ? Crew->GetHomeBoat() : nullptr;
	FString Text;
	if (bLoudhailer)
	{
		Text = FString::Printf(TEXT("[Loudhailer] %s: %s"), *Speaker, *Line);
		if (IsValid(FromBoat) && SquelchOpen)
		{
			UGameplayStatics::PlaySoundAtLocation(this, SquelchOpen, FromBoat->GetLoudhailerHorn()->GetComponentLocation(), 1.6f, 0.7f);
		}
	}
	else
	{
		// Heard only on a radio tuned to it.
		if (!MyBoat || MyBoat->GetRadioChannel() != Channel)
		{
			return;
		}
		Text = FString::Printf(TEXT("[CB %d] %s: %s"), Channel, *Speaker, *Line);
		if (SquelchOpen)
		{
			UGameplayStatics::PlaySoundAtLocation(this, SquelchOpen, MyBoat->GetRadioSpeaker()->GetComponentLocation());
		}
	}
	LastHeardLine = Text;
	HeardLines.Add({ Text, FPlatformTime::Seconds() + LineSeconds });
	if (HeardLines.Num() > 4)
	{
		HeardLines.RemoveAt(0);
	}
	UE_LOG(LogTemp, Log, TEXT("Riptide: heard %s"), *Text);
}

void URiptideVoiceComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);
	// The controller's input component only exists once it has set up its input (after this begins play).
	if (!VoiceMapping)
	{
		BuildInput();
	}
	UpdateTalkers();
	const double Now = FPlatformTime::Seconds();
	HeardLines.RemoveAll([Now](const FHeardLine& L) { return L.Until < Now; });
	DrawHud();
}

void URiptideVoiceComponent::DrawHud() const
{
	if (!GEngine)
	{
		return;
	}
	// Temporary readouts until the real HUD exists (keys above the crew's and the boat's prompts).
	const uint64 KeyBase = 0x52495054ull + 20;
	const APlayerController* PC = Cast<APlayerController>(GetOwner());
	const ARiptideCharacter* Crew = PC ? CrewOf(PC->PlayerState) : nullptr;
	const ARiptideBoat* Boat = RadioInReach();
	const bool bHolding = Boat && Boat->GetMicHolder() == Crew;
	if (bHolding)
	{
		const bool bHailer = Boat->GetMicMode() == ERiptideMicMode::Loudhailer;
		const FString Mode = bHailer ? TEXT("LOUDHAILER") : FString::Printf(TEXT("CB channel %d"), Boat->GetRadioChannel());
		GEngine->AddOnScreenDebugMessage(KeyBase + 0, 0.f, bPushToTalk ? FColor(255, 90, 70) : FColor(120, 215, 255),
			FString::Printf(TEXT("%s%s      Hold V  Talk      [ ]  Channel      B  %s"), bPushToTalk ? TEXT("TRANSMITTING  ") : TEXT(""), *Mode,
				bHailer ? TEXT("Switch to the CB") : TEXT("Switch to the loudhailer")));
	}
	else if (Boat)
	{
		GEngine->AddOnScreenDebugMessage(KeyBase + 0, 0.f, FColor(120, 215, 255),
			FString::Printf(TEXT("Radio: CB channel %d      [ ]  Channel"), Boat->GetRadioChannel()));
	}
	else if (bPushToTalk)
	{
		GEngine->AddOnScreenDebugMessage(KeyBase + 0, 0.f, FColor(255, 90, 70), TEXT("Talking"));
	}
	for (int32 i = 0; i < HeardLines.Num(); ++i)
	{
		GEngine->AddOnScreenDebugMessage(KeyBase + 1 + i, 0.f, FColor(255, 220, 140), HeardLines[i].Text);
	}
}

// --- NPC voices ---

void URiptideRadioSubsystem::Broadcast(int32 Channel, const FString& Speaker, const FString& Line)
{
	UWorld* World = GetWorld();
	if (!World || World->GetNetMode() == NM_Client)
	{
		return;
	}
	for (FConstPlayerControllerIterator It = World->GetPlayerControllerIterator(); It; ++It)
	{
		if (ARiptidePlayerController* PC = Cast<ARiptidePlayerController>(It->Get()))
		{
			PC->ClientRadioLine(Channel, nullptr, Speaker, Line, false);
		}
	}
}

void URiptideRadioSubsystem::RadioCall(const UObject* WorldContextObject, int32 Channel, const FString& Speaker, const FString& Line)
{
	const UWorld* World = GEngine ? GEngine->GetWorldFromContextObject(WorldContextObject, EGetWorldErrorMode::LogAndReturnNull) : nullptr;
	URiptideRadioSubsystem* Radio = World ? World->GetSubsystem<URiptideRadioSubsystem>() : nullptr;
	if (!Radio)
	{
		return;
	}
	// Sent on the next tick, not from inside the caller: a Python script runs with the editor's script guard up, under
	// which every network call runs locally instead of going out to the clients.
	TWeakObjectPtr<URiptideRadioSubsystem> WeakRadio(Radio);
	World->GetTimerManager().SetTimerForNextTick([WeakRadio, Channel, Speaker, Line]()
	{
		if (URiptideRadioSubsystem* R = WeakRadio.Get())
		{
			R->Broadcast(Channel, Speaker, Line);
		}
	});
}

void URiptideRadioSubsystem::Loudhailer(ARiptideBoat* Boat, const FString& Speaker, const FString& Line)
{
	UWorld* World = GetWorld();
	if (!World || World->GetNetMode() == NM_Client || !IsValid(Boat))
	{
		return;
	}
	constexpr float Earshot = 15000.f;
	for (FConstPlayerControllerIterator It = World->GetPlayerControllerIterator(); It; ++It)
	{
		ARiptidePlayerController* PC = Cast<ARiptidePlayerController>(It->Get());
		const ARiptideCharacter* Crew = PC ? URiptideVoiceComponent::CrewOf(PC->PlayerState) : nullptr;
		if (Crew && FVector::Dist(Crew->GetActorLocation(), Boat->GetActorLocation()) <= Earshot)
		{
			PC->ClientRadioLine(0, Boat, Speaker, Line, true);
		}
	}
}
