#pragma once

#include "CoreMinimal.h"
#include "Components/SkeletalMeshComponent.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "RiptideAppearance.h"
#include "RiptideCrewAnimInstance.h"
#include "RiptideCrewBody.generated.h"

class UMaterialInstanceDynamic;
class UStaticMeshComponent;

/**
 * A crew member's body, built from a look (FRiptideAppearance): the male or female body in the chosen skin tone,
 * and on it, each a skeletal mesh following this one's pose (leader pose, so they cost no extra animation), the
 * uniform in its camouflage, boots, gloves, hair and beard in their colour, headgear, face cover, vest and pack in
 * the gear colour. Animated in code by URiptideCrewAnimInstance.
 *
 * ARiptideCharacter uses it as its mesh. To show a crew member anywhere else (the main menu, the customisation
 * screen) use ARiptideCrewMannequin, or add this component to any actor:
 *
 *     Body->SetAppearance(Look);                       // builds (or rebuilds) the body; cheap to call again
 *     Body->SetPose(ERiptideCrewPose::RifleReady);     // or Idle; Gameplay follows an owning ARiptideCharacter
 *
 * The component's origin is at the feet, and the body faces the component's +Y: rotate it -90 degrees in yaw to
 * face its owner's forward (+X). The male body stands 1.81 m tall, the female 1.77 m. Meshes and materials are
 * generated by Content/Python/init_unreal.py (riptide_crew_mesh.py) under /Game/Riptide/Characters and loaded by
 * path.
 */
UCLASS(ClassGroup = (Riptide), meta = (BlueprintSpawnableComponent))
class RIPTIDE_API URiptideCrewBodyComponent : public USkeletalMeshComponent
{
	GENERATED_BODY()

public:
	URiptideCrewBodyComponent(const FObjectInitializer& ObjectInitializer);

	/** Builds the body for this look: swaps the meshes and sets the colours. Only what changed is redone. */
	UFUNCTION(BlueprintCallable, Category = "Crew")
	void SetAppearance(const FRiptideAppearance& Look);

	UFUNCTION(BlueprintPure, Category = "Crew")
	const FRiptideAppearance& GetAppearance() const { return Appearance; }

	/** What the body does: follow its ARiptideCharacter (Gameplay), stand at ease, or hold the rifle shouldered
	 * (the rifle shows only in that pose). */
	UFUNCTION(BlueprintCallable, Category = "Crew")
	void SetPose(ERiptideCrewPose NewPose);

	UFUNCTION(BlueprintPure, Category = "Crew")
	ERiptideCrewPose GetPose() const { return Pose; }

	/** Hides the body (and everything worn) from its owner's own view (a first-person player), still casting its
	 * shadow; others see it. */
	UFUNCTION(BlueprintCallable, Category = "Crew")
	void SetHiddenFromOwner(bool bHide);

	/** The owner's own first-person view of this body: the head and what's on it aren't drawn for them (the camera
	 * is inside it), while a shadow-only copy keeps the whole figure's shadow on the ground. Others see all of it. */
	UFUNCTION(BlueprintCallable, Category = "Crew")
	void SetFirstPersonView(bool bOn);

	/** Poses the body every frame even off screen (as a player's own body always is); for tests without a renderer. */
	UFUNCTION(BlueprintCallable, Category = "Crew")
	void SetAlwaysPosed(bool bAlways)
	{
		VisibilityBasedAnimTickOption = bAlways || bFirstPerson || bHiddenFromOwner ? EVisibilityBasedAnimTickOption::AlwaysTickPoseAndRefreshBones
			: EVisibilityBasedAnimTickOption::OnlyTickPoseWhenRendered;
	}

	UFUNCTION(BlueprintPure, Category = "Crew")
	bool IsFirstPersonView() const { return bFirstPerson; }

	/** What the animation shows now (for tests). */
	UFUNCTION(BlueprintPure, Category = "Crew")
	ERiptideCrewAnimState GetAnimState() const;

	/** The meshes worn, one "Part=Mesh" per part separated by spaces (Body=SK_CrewMale Uniform=SK_Uniform ...),
	 * for tests and logs. Parts not worn are left out. */
	UFUNCTION(BlueprintPure, Category = "Crew")
	FString DescribeParts() const;

	/** True once a body mesh has loaded (false if the generated assets are missing). */
	UFUNCTION(BlueprintPure, Category = "Crew")
	bool HasBody() const { return GetSkeletalMeshAsset() != nullptr; }

	// The rifle in the RifleReady pose, shouldered: placed from the body (its stock in the right shoulder's pocket,
	// its sights at the eye), aimed along the body's facing tipped down a little. Shared with the animation, which
	// puts the hands on it.
	static FQuat RifleAim() { return FQuat(FVector(1.f, 0.f, 0.f), FMath::DegreesToRadians(-4.f)); }

	/** The rifle model's placement in the body's component space, from the posed right upper arm and head. */
	static FTransform RifleInComponent(const FVector& UpperArmR, const FVector& Head);

	/** A fishing rod held in both hands, in the body's component space: the origin where the right hand holds it (at
	 * the reel seat), X along the rod to its tip, Y down toward the reel. Pitch is where the crew member looks (up +,
	 * degrees); Swing how it's being worked (URiptideAnglerComponent::GetRodSwing: 1 wound back over the shoulder,
	 * negative flicked out). The reel hangs under the right hand, the left hand on its crank. Shared with the
	 * animation. */
	static FTransform RodInComponent(const FVector& UpperArmR, float Pitch, float Swing);

	/** The tip of what's held (the rod's), in the world. False when nothing is held or it isn't shown. */
	bool GetHeldTip(FVector& OutTip) const;

	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;
	virtual void OnUnregister() override;

private:
	/** The parts worn on the body, each its own mesh following the body's pose. */
	enum class EPart : uint8 { Uniform, Boots, Gloves, Hair, Beard, Headgear, FaceCover, Vest, Pack, Shirt, Shorts, Footwear, Count };

	USkeletalMeshComponent* PartComponent(EPart Part);
	void SetPart(EPart Part, const TCHAR* MeshName);
	/** The material to draw a slot with, with this look's colours set (one dynamic instance per material). */
	UMaterialInterface* Coloured(UMaterialInterface* Material);
	void ColourAll();
	void ApplyOwnerVisibility(UPrimitiveComponent* Component, EPart Part = EPart::Count) const;
	void UpdateRifle();
	/** Shows what the owning character holds, placed in its hands. */
	void UpdateHeld();
	/** Hides the head for the owner and keeps the shadow copy in step with the body (after a rebuild). */
	void ApplyFirstPerson();

	UPROPERTY(Transient)
	TArray<TObjectPtr<USkeletalMeshComponent>> Parts;

	UPROPERTY(Transient)
	TObjectPtr<UStaticMeshComponent> Rifle;

	/** What's in the hands (the fishing rod), and where on its model the right hand holds it and its tip are. */
	UPROPERTY(Transient)
	TObjectPtr<UStaticMeshComponent> Held;
	FName HeldShown;
	FVector HeldGrip = FVector::ZeroVector;
	FVector HeldTip = FVector::ZeroVector;

	/** The whole body again, drawn for nobody, there only for its shadow in the owner's first-person view. */
	UPROPERTY(Transient)
	TObjectPtr<USkeletalMeshComponent> ShadowBody;

	bool bFirstPerson = false;

	/** Dynamic instances by the material they were made from. */
	UPROPERTY(Transient)
	TMap<TObjectPtr<UMaterialInterface>, TObjectPtr<UMaterialInstanceDynamic>> Dynamic;

	FRiptideAppearance Appearance;
	bool bBuilt = false;
	bool bHiddenFromOwner = false;
	ERiptideCrewPose Pose = ERiptideCrewPose::Gameplay;
};

/** Helpers for the editor's import script (init_unreal.py), which can only call UFUNCTIONs. */
UCLASS()
class RIPTIDE_API URiptideCrewLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	/** The crew's animation clips: "AssetName=UAL1/ClipName" each (the asset names the anim instance loads, and the
	 * Quaternius library and clip each is imported from). */
	UFUNCTION(BlueprintCallable, Category = "Crew|Editor")
	static TArray<FString> GetCrewClips();

	/** Sets up the crew's shared skeleton so one set of animations fits both bodies: every bone takes its length from
	 * the body playing the animation (not from the animation's own rig), except the root and pelvis, which move as
	 * animated (URiptideCrewAnimInstance scales the hips' height to the body's legs). Editor only; true if done. */
	UFUNCTION(BlueprintCallable, Category = "Crew|Editor")
	static bool SetUpCrewSkeleton(USkeleton* Skeleton);

	/** Puts a crew member (with no player) on a boat in this look, standing at Location facing Yaw: for automated
	 * tests and screenshots (Python can't spawn into a running game), and AI crews to come. Server only. */
	UFUNCTION(BlueprintCallable, Category = "Crew", meta = (WorldContext = "WorldContextObject"))
	static class ARiptideCharacter* SpawnCrewMember(UObject* WorldContextObject, class ARiptideBoat* Boat, FVector Location, float Yaw,
		const FRiptideAppearance& Look);

	/** Places a menu mannequin (ARiptideCrewMannequin) in this look and pose, its feet at Location facing Yaw. */
	UFUNCTION(BlueprintCallable, Category = "Crew", meta = (WorldContext = "WorldContextObject"))
	static class ARiptideCrewMannequin* SpawnMannequin(UObject* WorldContextObject, FVector Location, float Yaw, const FRiptideAppearance& Look,
		ERiptideCrewPose Pose);
};
