#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Pawn.h"
#include "RiptideBoat.generated.h"

class ARiptideCharacter;
class UAudioComponent;
class UStaticMesh;
class UMaterialInterface;
class UNiagaraSystem;
class URiptideWakeFoamComponent;
class UBoxComponent;
class UStaticMeshComponent;
class UBuoyancyComponent;
class UCameraComponent;
class USoundAttenuation;
class USoundBase;
class UInputAction;
class UInputMappingContext;
struct FInputActionValue;

/**
 * Motorboat driven from the helm in first person.
 *
 * Handling is physics-driven: an outboard motor pushes from the stern only while the
 * propeller is underwater, and steering swings the motor so the thrust itself turns the
 * boat. That means the boat barely turns at idle, loses drive when it catches air off a
 * swell, and slides through turns until the keel bites.
 */
UCLASS()
class RIPTIDE_API ARiptideBoat : public APawn
{
	GENERATED_BODY()

public:
	ARiptideBoat();

	virtual void Tick(float DeltaSeconds) override;
	virtual void SetupPlayerInputComponent(UInputComponent* PlayerInputComponent) override;
	virtual void NotifyControllerChanged() override;
	virtual void UnPossessed() override;
	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;

	UFUNCTION(BlueprintPure, Category = "Boat")
	float GetSpeedKnots() const;

	UFUNCTION(BlueprintPure, Category = "Boat")
	bool IsPropellerSubmerged() const;

	UFUNCTION(BlueprintCallable, Category = "Boat")
	void ApplyEngineDamage(float Amount);

	/**
	 * Holds the helm controls as if keys were held: Throttle moves the lever (-1..1), Steer swings the motor (-1..1).
	 * For AI helmsmen and automated handling tests; players drive through input. Server only.
	 */
	UFUNCTION(BlueprintCallable, Category = "Boat")
	void SetHelmInput(float Throttle, float Steer);

	UFUNCTION(BlueprintPure, Category = "Boat")
	float GetThrottleLever() const { return ThrottleLever; }

	UFUNCTION(BlueprintPure, Category = "Boat")
	float GetEngineOutput() const { return EngineOutput; }

	UFUNCTION(BlueprintPure, Category = "Boat")
	float GetFuelLiters() const { return FuelLiters; }

	/** Height of the bow's deck edge above the water there, in cm. Negative means the bow is under. */
	UFUNCTION(BlueprintPure, Category = "Boat")
	float GetBowFreeboardCm() const;

	// --- Crew ---

	/** Where the helmsman stands, behind the console, facing forward: a point on the deck, in the world. */
	UFUNCTION(BlueprintPure, Category = "Boat|Crew")
	FTransform GetHelmStandTransform() const;

	/** A spot on the deck to put a crew member (0 = the helm, then the aft deck and the foredeck), in the world. */
	UFUNCTION(BlueprintPure, Category = "Boat|Crew")
	FTransform GetDeckSpotTransform(int32 Index) const;

	/** Whoever is driving, or null. */
	UFUNCTION(BlueprintPure, Category = "Boat|Crew")
	ARiptideCharacter* GetHelmsman() const { return Helmsman; }

	/** Puts a crew member at the helm: their player now drives the boat. False if someone already has it. Server only. */
	bool TakeHelm(ARiptideCharacter* Crew);

	/** The helmsman lets go of the wheel and stands back on the deck (the throttle stays where it was left). */
	UFUNCTION(BlueprintCallable, Category = "Boat|Crew")
	void LeaveHelm();

	/** Throws spray off the bow, as when it slaps into a wave. Strength 0..1 sets how big. */
	UFUNCTION(BlueprintCallable, Category = "Boat")
	void SprayAtBow(float Strength);

protected:
	UPROPERTY(VisibleAnywhere, Category = "Boat")
	TObjectPtr<UBoxComponent> HullBody;

	UPROPERTY(VisibleAnywhere, Category = "Boat")
	TObjectPtr<UStaticMeshComponent> HullMesh;

	/** Twin outboards on the transom, port and starboard. They steer together. */
	UPROPERTY(VisibleAnywhere, Category = "Boat")
	TObjectPtr<UStaticMeshComponent> MotorMesh;

	UPROPERTY(VisibleAnywhere, Category = "Boat")
	TObjectPtr<UStaticMeshComponent> MotorMeshStarboard;

	/**
	 * What the crew walks on: the hull model's own triangles (deck, bulwarks, console, T-top legs, rails), invisible.
	 * It's separate from the physics body so it can be the exact concave shape of the deck, and only the crew
	 * collides with it. It rides along with the hull rather than being part of its physics.
	 */
	UPROPERTY(VisibleAnywhere, Category = "Boat")
	TObjectPtr<UStaticMeshComponent> DeckCollision;

	/** The boat and outboard models (generated by Content/Python/riptide_boat_mesh.py). */
	UPROPERTY(EditAnywhere, Category = "Boat")
	TSoftObjectPtr<UStaticMesh> HullModel;

	UPROPERTY(EditAnywhere, Category = "Boat")
	TSoftObjectPtr<UStaticMesh> OutboardModel;

	/** The two props, where each motor's thrust pushes. */
	UPROPERTY(VisibleAnywhere, Category = "Boat")
	TObjectPtr<USceneComponent> Propeller;

	UPROPERTY(VisibleAnywhere, Category = "Boat")
	TObjectPtr<USceneComponent> PropellerStarboard;

	UPROPERTY(VisibleAnywhere, Category = "Boat")
	TObjectPtr<UCameraComponent> HelmCamera;

	// The wake is the Water plugin's fluid simulation (BP_FluidSim_01): a ripple solver on a patch of water that
	// follows the player. The hull pushes it with Epic's boat force (a hull-shaped push plus foam), so the waves
	// and foam form a real V behind the boat. The push's strength comes from the hull's speed; how hard that
	// disturbs the water is set by HeightScale and FoamScale on MI_WakeForce (Content/Python/init_unreal.py).

	/** Point at the hull's waterline that pushes the wake simulation. */
	UPROPERTY(VisibleAnywhere, Category = "Boat|Wake")
	TObjectPtr<USceneComponent> WakeSource;

	/** Material the wake simulation draws the hull's push with. */
	UPROPERTY(EditAnywhere, Category = "Boat|Wake")
	TSoftObjectPtr<UMaterialInterface> WakeForceMaterial;

	/** Half the length of the hull's footprint on the wake simulation, in cm. */
	UPROPERTY(EditAnywhere, Category = "Boat|Wake")
	float WakeRadius = 395.f;

	/** Size of the patch of water the wake simulation covers around the player, in cm. Bigger makes a longer
	 * wake at a coarser grid (the simulation is 1024 cells across). */
	UPROPERTY(EditAnywhere, Category = "Boat|Wake")
	float WakeSimulationSize = 8192.f;

	/** How fast ripples cross the simulation, in grid cells per step (at most 1). With the patch size this sets
	 * the ripple speed, and the V opens wider the closer that gets to the boat's speed. 0.45 on an 80 m patch is
	 * about 3.2 m/s, giving a V close to a real wake at cruising speed. */
	UPROPERTY(EditAnywhere, Category = "Boat|Wake")
	float WakeSimulationWaveSpeed = 0.45f;

	/** How quickly the simulation's ripples die out. Low keeps the V's arms trailing well behind the boat;
	 * high (the simulation's own 0.05 and up) smothers them. */
	UPROPERTY(EditAnywhere, Category = "Boat|Wake")
	float WakeSimulationDamping = 0.02f;

	/** White foam on the water: churned water behind the transom and wash peeling off the bow. */
	UPROPERTY(VisibleAnywhere, Category = "Boat|Wake")
	TObjectPtr<URiptideWakeFoamComponent> WakeFoam;

	UPROPERTY(EditAnywhere, Category = "Boat|Wake")
	TSoftObjectPtr<UMaterialInterface> WakeFoamMaterial;

	/** Speed at which the foam is at its thickest. */
	UPROPERTY(EditAnywhere, Category = "Boat|Wake")
	float FoamFullSpeedKnots = 12.f;

	/** Spray thrown up when the bow slaps into a wave. */
	UPROPERTY(EditAnywhere, Category = "Boat|Wake")
	TSoftObjectPtr<UNiagaraSystem> BowSpraySystem;

	// --- Sound ---
	// Levels are set on the sound assets themselves (see Content/Python/init_unreal.py), so volume 1 here is
	// the loudest each should get: the engine at full throttle, the wash at top speed.

	// The engine is two recordings of a real outboard, one at low revs and one at high revs. Both are pitched to the
	// same engine speed and crossfaded, so the motor sounds right across the whole throttle range. Each of the twin
	// motors plays its own pair, a touch out of tune with the other like two real engines, each at half power so
	// together they're as loud as the single engine the levels were set for.

	UPROPERTY(VisibleAnywhere, Category = "Boat|Sound")
	TObjectPtr<UAudioComponent> EngineAudio;

	UPROPERTY(VisibleAnywhere, Category = "Boat|Sound")
	TObjectPtr<UAudioComponent> EngineHighAudio;

	UPROPERTY(VisibleAnywhere, Category = "Boat|Sound")
	TObjectPtr<UAudioComponent> EngineAudioStarboard;

	UPROPERTY(VisibleAnywhere, Category = "Boat|Sound")
	TObjectPtr<UAudioComponent> EngineHighAudioStarboard;

	/** How far the starboard engine runs off the port one's pitch (1.01 = 1% faster). */
	UPROPERTY(EditAnywhere, Category = "Boat|Sound")
	float StarboardEngineDetune = 1.012f;

	UPROPERTY(VisibleAnywhere, Category = "Boat|Sound")
	TObjectPtr<UAudioComponent> WashAudio;

	UPROPERTY(EditAnywhere, Category = "Boat|Sound")
	TSoftObjectPtr<USoundBase> EngineSound;

	UPROPERTY(EditAnywhere, Category = "Boat|Sound")
	TSoftObjectPtr<USoundBase> EngineHighSound;

	/** The engine's firing pitch in the low- and high-rev recordings (Hz), found from their spectra. */
	UPROPERTY(EditAnywhere, Category = "Boat|Sound")
	float EngineLowRecordingHz = 25.6f;

	UPROPERTY(EditAnywhere, Category = "Boat|Sound")
	float EngineHighRecordingHz = 73.f;

	UPROPERTY(EditAnywhere, Category = "Boat|Sound")
	TSoftObjectPtr<USoundBase> WashSound;

	/** Played at random when the bow slams into a wave. */
	UPROPERTY(EditAnywhere, Category = "Boat|Sound")
	TArray<TSoftObjectPtr<USoundBase>> HullSlapSounds;

	/** Engine firing pitch at idle and at full revs (Hz). */
	UPROPERTY(EditAnywhere, Category = "Boat|Sound")
	float EngineIdleHz = 25.6f;

	UPROPERTY(EditAnywhere, Category = "Boat|Sound")
	float EngineFullHz = 73.f;

	/** Engine loop volume at idle, as a fraction of full throttle. */
	UPROPERTY(EditAnywhere, Category = "Boat|Sound", meta = (ClampMin = "0", ClampMax = "1"))
	float EngineIdleVolume = 0.4f;

	/** Extra revs when the prop comes out of the water and the engine races, as a fraction of full revs. */
	UPROPERTY(EditAnywhere, Category = "Boat|Sound", meta = (ClampMin = "0", ClampMax = "1"))
	float PropOutOverRev = 0.3f;

	/** Speed at which the hull wash reaches full volume. */
	UPROPERTY(EditAnywhere, Category = "Boat|Sound")
	float WashFullSpeedKnots = 16.f;

	/** How fast the bow must meet the water for a slap (cm/s), and the speed of the loudest slap. */
	UPROPERTY(EditAnywhere, Category = "Boat|Sound")
	float SlapMinSpeed = 120.f;

	UPROPERTY(EditAnywhere, Category = "Boat|Sound")
	float SlapFullSpeed = 450.f;

	/** Shortest gap between slaps, in seconds. */
	UPROPERTY(EditAnywhere, Category = "Boat|Sound")
	float SlapCooldown = 0.35f;

	UPROPERTY(VisibleAnywhere, Category = "Boat")
	TObjectPtr<UBuoyancyComponent> Buoyancy;

	// --- Hull ---

	UPROPERTY(EditAnywhere, Category = "Boat|Hull", meta = (ClampMin = "50"))
	float HullMassKg = 2000.f;

	/** Water resistance moving forward (N per (m/s)^2). Sets top speed. */
	UPROPERTY(EditAnywhere, Category = "Boat|Hull")
	float ForwardDrag = 122.f;

	/** Water resistance moving sideways (N per (m/s)^2). The keel: higher = less sliding in turns. */
	UPROPERTY(EditAnywhere, Category = "Boat|Hull")
	float LateralDrag = 2000.f;

	/** Water resistance to bobbing up and down (N per m/s). Higher = the hull settles faster after a wave. */
	UPROPERTY(EditAnywhere, Category = "Boat|Hull")
	float HeaveDamping = 13300.f;

	/** How quickly the hull stops spinning, in 1/s. */
	UPROPERTY(EditAnywhere, Category = "Boat|Hull")
	float YawDamping = 1.2f;

	/** How quickly roll and pitch rocking dies out in the water, in 1/s. */
	UPROPERTY(EditAnywhere, Category = "Boat|Hull")
	float RockDamping = 6.f;

	/**
	 * Hydrodynamic lift on the forward hull as it moves (N per (m/s)^2 of forward speed). Pushes the bow up
	 * at speed so it rides over swells instead of burying. Only acts where the forward hull is in the water.
	 */
	UPROPERTY(EditAnywhere, Category = "Boat|Hull")
	float PlaningLift = 155.f;

	/** Largest planing lift as a fraction of the boat's weight, so jumps off wave crests don't launch it. */
	UPROPERTY(EditAnywhere, Category = "Boat|Hull", meta = (ClampMin = "0", ClampMax = "1"))
	float MaxPlaningLiftFraction = 0.5f;

	// --- Engine ---

	/** Thrust of both motors together at full throttle, in Newtons. Each motor gives half, and only while its prop is
	 * in the water. Mass, drag and thrust are scaled together from the tuned 6 m skiff, so the handling feels the same. */
	UPROPERTY(EditAnywhere, Category = "Boat|Engine")
	float MaxThrust = 7800.f;

	/** Fraction of forward thrust available in reverse. */
	UPROPERTY(EditAnywhere, Category = "Boat|Engine", meta = (ClampMin = "0", ClampMax = "1"))
	float ReverseThrustScale = 0.4f;

	/** How fast the throttle lever moves while the key is held, in full-range per second. */
	UPROPERTY(EditAnywhere, Category = "Boat|Engine")
	float ThrottleLeverRate = 0.6f;

	/** How fast the engine spools toward the lever position. */
	UPROPERTY(EditAnywhere, Category = "Boat|Engine")
	float EngineSpoolRate = 1.5f;

	UPROPERTY(EditAnywhere, Category = "Boat|Engine")
	float MaxSteerAngleDeg = 30.f;

	/** How fast the motor swings when steering, in degrees per second. */
	UPROPERTY(EditAnywhere, Category = "Boat|Engine")
	float SteerRateDeg = 70.f;

	UPROPERTY(EditAnywhere, Category = "Boat|Engine")
	float FuelCapacityLiters = 40.f;

	/** Fuel burned per second at full throttle. */
	UPROPERTY(EditAnywhere, Category = "Boat|Engine")
	float FuelBurnPerSecond = 0.02f;

	// --- Camera ---

	UPROPERTY(EditAnywhere, Category = "Boat|Camera")
	float LookSensitivity = 1.f;

	// --- Replicated state (server-authoritative) ---

	/** Throttle lever position, -1 (full reverse) to 1 (full ahead). The lever stays where you leave it. */
	UPROPERTY(Replicated, VisibleInstanceOnly, Category = "Boat|State")
	float ThrottleLever = 0.f;

	/** Actual engine output, lagging behind the lever. */
	UPROPERTY(Replicated, VisibleInstanceOnly, Category = "Boat|State")
	float EngineOutput = 0.f;

	UPROPERTY(Replicated, VisibleInstanceOnly, Category = "Boat|State")
	float SteerAngleDeg = 0.f;

	UPROPERTY(Replicated, VisibleInstanceOnly, Category = "Boat|State")
	float FuelLiters = 0.f;

	/** 1 = healthy. Below 0.5 the engine sputters; at 0 it's dead. */
	UPROPERTY(Replicated, VisibleInstanceOnly, Category = "Boat|State")
	float EngineHealth = 1.f;

	virtual void BeginPlay() override;
	virtual void OnConstruction(const FTransform& Transform) override;

	/** Swaps the placeholder shapes for the boat models, if they've been built. */
	void ApplyModels();

private:
	void BuildInput();
	void UpdateControls(float DeltaSeconds);
	void UpdateEngine(float DeltaSeconds);
	void ApplyThrust();
	void ApplyHydrodynamics();
	void DrawDebugHud() const;
	bool IsPropSubmerged(const USceneComponent* Prop) const;
	void RegisterWithWakeSimulation();
	AActor* SpawnWakeSimulation(UClass* SimClass);
	void StartSounds();
	void UpdateSounds(float DeltaSeconds);
	void StartWakeFoam();
	void UpdateWakeFoam(float DeltaSeconds);

	void OnThrottle(const FInputActionValue& Value);
	void OnThrottleReleased(const FInputActionValue& Value);
	void OnSteer(const FInputActionValue& Value);
	void OnSteerReleased(const FInputActionValue& Value);
	void OnCutThrottle(const FInputActionValue& Value);
	void OnLook(const FInputActionValue& Value);
	void OnLeaveHelm(const FInputActionValue& Value);

	UFUNCTION(Server, Reliable)
	void ServerLeaveHelm();

	UFUNCTION(Server, Unreliable)
	void ServerSetControls(float InThrottleInput, float InSteerInput, bool bInCutThrottle);

	UPROPERTY(Transient)
	TObjectPtr<UInputMappingContext> HelmMapping;

	UPROPERTY(Transient)
	TObjectPtr<UInputAction> ThrottleAction;

	UPROPERTY(Transient)
	TObjectPtr<UInputAction> SteerAction;

	UPROPERTY(Transient)
	TObjectPtr<UInputAction> CutThrottleAction;

	UPROPERTY(Transient)
	TObjectPtr<UInputAction> LookAction;

	UPROPERTY(Transient)
	TObjectPtr<UInputAction> LeaveHelmAction;

	UPROPERTY(Replicated, Transient)
	TObjectPtr<ARiptideCharacter> Helmsman;

	// Raw input from whoever is at the helm. On the server these come from ServerSetControls.
	float ThrottleInput = 0.f;
	float SteerInput = 0.f;
	bool bCutThrottleRequested = false;

	float LookYaw = 0.f;
	float LookPitch = 0.f;

	/** Remaining time the engine is cut out by a sputter. */
	float SputterTimeLeft = 0.f;

	/** Index of the buoyancy pontoon nearest the propeller, used to read the water height there. */
	int32 SternPontoonIndex = INDEX_NONE;

	/** Index of a bow pontoon, used to read the water height at the bow. */
	int32 BowPontoonIndex = INDEX_NONE;

	/** Distance falloff shared by the boat's sounds, so other boats fade with distance. */
	UPROPERTY(Transient)
	TObjectPtr<USoundAttenuation> SoundFalloff;

	int32 SternFoamTrail = INDEX_NONE;
	float ChurnLevel = 0.f;

	bool bEngineSoundRunning = false;
	float EngineRevs = 0.f;
	float PrevBowFreeboard = 0.f;
	bool bHaveBowFreeboard = false;
	float SlapCooldownLeft = 0.f;
};
