#include "RiptideBoat.h"

#include "BuoyancyComponent.h"
#include "Camera/CameraComponent.h"
#include "Components/AudioComponent.h"
#include "Components/BoxComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/CollisionProfile.h"
#include "Engine/Engine.h"
#include "Engine/LocalPlayer.h"
#include "Engine/StaticMesh.h"
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"
#include "GameFramework/PlayerController.h"
#include "InputAction.h"
#include "InputMappingContext.h"
#include "InputModifiers.h"
#include "Kismet/GameplayStatics.h"
#include "UObject/StructOnScope.h"
#include "Materials/MaterialInterface.h"
#include "Misc/App.h"
#include "NiagaraFunctionLibrary.h"
#include "NiagaraSystem.h"
#include "RiptideWakeFoamComponent.h"
#include "WaterBodyComponent.h"
#include "WaterBodyOceanActor.h"
#include "Net/UnrealNetwork.h"
#include "Sound/SoundAttenuation.h"
#include "Sound/SoundBase.h"
#include "UObject/ConstructorHelpers.h"

DEFINE_LOG_CATEGORY_STATIC(LogRiptideBoat, Log, All);

namespace
{
	// Unreal works in centimetres, so forces in Newtons are scaled by 100 (kg*cm/s^2).
	constexpr float NewtonsToUnreal = 100.f;
	constexpr float CmPerSecToKnots = 0.0194384f;

	// Hull size in cm (length, beam, depth) for the placeholder skiff.
	const FVector HullExtent(300.f, 110.f, 35.f);

	// Buoyancy pontoons, in cm. They sit only a quarter of their height in the water at rest, so the hull
	// has about six times its resting lift in reserve: a bow driven into a swell gets pushed back up hard
	// instead of burying. The waterline sits 20 cm up the hull.
	constexpr float PontoonRadius = 60.f;
	constexpr float PontoonRestDepth = 30.f;

	// The outboard model's steering pivot on the transom, and its prop relative to that pivot
	// (see build_outboard in Content/Python/riptide_boat_mesh.py).
	const FVector OutboardPivot(-HullExtent.X, 0.f, 15.f);
	const FVector PropInOutboard(-50.f, 0.f, -75.f);
	const float WaterlineZ = -HullExtent.Z + 20.f;
}

ARiptideBoat::ARiptideBoat()
{
	PrimaryActorTick.bCanEverTick = true;
	bReplicates = true;
	SetReplicatingMovement(true);

	static ConstructorHelpers::FObjectFinder<UStaticMesh> CubeMesh(TEXT("/Engine/BasicShapes/Cube.Cube"));
	static ConstructorHelpers::FObjectFinder<UStaticMesh> CylinderMesh(TEXT("/Engine/BasicShapes/Cylinder.Cylinder"));

	// The physics body is an unscaled box so pontoon and propeller offsets stay in real centimetres.
	HullBody = CreateDefaultSubobject<UBoxComponent>(TEXT("HullBody"));
	HullBody->SetBoxExtent(HullExtent);
	HullBody->SetCollisionProfileName(UCollisionProfile::PhysicsActor_ProfileName);
	HullBody->SetSimulatePhysics(true);
	// Set the override directly: SetMassOverrideInKg recalculates mass, which can't run during CDO construction.
	HullBody->BodyInstance.SetMassOverride(HullMassKg, true);
	HullBody->SetLinearDamping(0.f);
	HullBody->SetAngularDamping(0.5f);
	RootComponent = HullBody;

	// Placeholder visuals, replaced by the boat model in ApplyModels.
	HullMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("HullMesh"));
	HullMesh->SetupAttachment(HullBody);
	HullMesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	HullMesh->SetRelativeScale3D(HullExtent / 50.f);
	if (CubeMesh.Succeeded())
	{
		HullMesh->SetStaticMesh(CubeMesh.Object);
	}

	MotorMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MotorMesh"));
	MotorMesh->SetupAttachment(HullBody);
	MotorMesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	MotorMesh->SetRelativeLocation(FVector(-HullExtent.X - 15.f, 0.f, -10.f));
	MotorMesh->SetRelativeScale3D(FVector(0.25f, 0.25f, 0.9f));
	if (CylinderMesh.Succeeded())
	{
		MotorMesh->SetStaticMesh(CylinderMesh.Object);
	}

	// The boat model, generated by Content/Python/riptide_boat_mesh.py and imported when the editor opens. The
	// box and cylinder above stand in until it exists (on the very first launch).
	HullModel = TSoftObjectPtr<UStaticMesh>(FSoftObjectPath(TEXT("/Game/Riptide/Boats/SM_PatrolSkiff.SM_PatrolSkiff")));
	OutboardModel = TSoftObjectPtr<UStaticMesh>(FSoftObjectPath(TEXT("/Game/Riptide/Boats/SM_Outboard.SM_Outboard")));

	// Propeller: at the outboard's prop, well below the waterline when the boat is level.
	Propeller = CreateDefaultSubobject<USceneComponent>(TEXT("Propeller"));
	Propeller->SetupAttachment(HullBody);
	Propeller->SetRelativeLocation(OutboardPivot + PropInOutboard);

	// Standing at the helm, just behind the console, eyes about 1.7 m above the deck.
	HelmCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("HelmCamera"));
	HelmCamera->SetupAttachment(HullBody);
	HelmCamera->SetRelativeLocation(FVector(-85.f, 0.f, 175.f));
	HelmCamera->bUsePawnControlRotation = false;

	// At the waterline, amidships.
	WakeSource = CreateDefaultSubobject<USceneComponent>(TEXT("WakeSource"));
	WakeSource->SetupAttachment(HullBody);
	WakeSource->SetRelativeLocation(FVector(0.f, 0.f, WaterlineZ));

	// Foam is laid in world space; the component ignores the hull's transform.
	WakeFoam = CreateDefaultSubobject<URiptideWakeFoamComponent>(TEXT("WakeFoam"));
	WakeFoam->SetupAttachment(HullBody);
	WakeFoamMaterial = TSoftObjectPtr<UMaterialInterface>(FSoftObjectPath(TEXT("/Game/Riptide/Materials/M_WakeFoam.M_WakeFoam")));
	WakeForceMaterial = TSoftObjectPtr<UMaterialInterface>(FSoftObjectPath(TEXT("/Game/Riptide/Materials/MI_WakeForce.MI_WakeForce")));
	// No bow spray effect yet: the engine's Niagara templates make sparks, not spray. SprayAtBow does nothing
	// until BowSpraySystem is set to a proper spray effect.

	// The engine sounds from the motor; the wash from the hull at the waterline.
	EngineAudio = CreateDefaultSubobject<UAudioComponent>(TEXT("EngineAudio"));
	EngineAudio->SetupAttachment(MotorMesh);
	EngineAudio->bAutoActivate = false;
	EngineHighAudio = CreateDefaultSubobject<UAudioComponent>(TEXT("EngineHighAudio"));
	EngineHighAudio->SetupAttachment(MotorMesh);
	EngineHighAudio->bAutoActivate = false;
	WashAudio = CreateDefaultSubobject<UAudioComponent>(TEXT("WashAudio"));
	WashAudio->SetupAttachment(HullBody);
	WashAudio->SetRelativeLocation(FVector(0.f, 0.f, WaterlineZ));
	WashAudio->bAutoActivate = false;

	// The sounds are imported by Content/Python/init_unreal.py when the editor opens, so they're referenced
	// by path and loaded at BeginPlay rather than looked up here.
	EngineSound = TSoftObjectPtr<USoundBase>(FSoftObjectPath(TEXT("/Game/Riptide/Audio/S_Engine_Low.S_Engine_Low")));
	EngineHighSound = TSoftObjectPtr<USoundBase>(FSoftObjectPath(TEXT("/Game/Riptide/Audio/S_Engine_High.S_Engine_High")));
	WashSound = TSoftObjectPtr<USoundBase>(FSoftObjectPath(TEXT("/Game/Riptide/Audio/S_Hull_Wash.S_Hull_Wash")));
	for (const TCHAR* Slap : { TEXT("04"), TEXT("06"), TEXT("08"), TEXT("13"), TEXT("15") })
	{
		HullSlapSounds.Add(TSoftObjectPtr<USoundBase>(FSoftObjectPath(
			FString::Printf(TEXT("/Game/Riptide/Audio/S_Hull_Slap_%s.S_Hull_Slap_%s"), Slap, Slap))));
	}

	// Weight sits low and aft (engine, fuel, crew on the floor), which keeps the hull from rolling over.
	HullBody->BodyInstance.COMNudge = FVector(-30.f, 0.f, -30.f);

	// Pontoons run down both sides, where the hull's width resists rolling, plus one at the stern
	// that also tells us if the prop is wet. BeginPlay sizes their lift so they float PontoonRestDepth deep.
	Buoyancy = CreateDefaultSubobject<UBuoyancyComponent>(TEXT("Buoyancy"));
	const float PontoonZ = WaterlineZ - PontoonRestDepth + PontoonRadius;
	const float ChineY = HullExtent.Y * 0.6f;
	const FVector PontoonOffsets[] = {
		FVector(HullExtent.X * 0.8f, ChineY, PontoonZ),
		FVector(HullExtent.X * 0.8f, -ChineY, PontoonZ),
		FVector(HullExtent.X * 0.27f, ChineY, PontoonZ),
		FVector(HullExtent.X * 0.27f, -ChineY, PontoonZ),
		FVector(-HullExtent.X * 0.27f, ChineY, PontoonZ),
		FVector(-HullExtent.X * 0.27f, -ChineY, PontoonZ),
		FVector(-HullExtent.X * 0.8f, ChineY, PontoonZ),
		FVector(-HullExtent.X * 0.8f, -ChineY, PontoonZ),
		FVector(-HullExtent.X, 0.f, PontoonZ),
	};
	for (const FVector& Offset : PontoonOffsets)
	{
		FSphericalPontoon Pontoon;
		Pontoon.RelativeLocation = Offset;
		Pontoon.Radius = PontoonRadius;
		Buoyancy->BuoyancyData.Pontoons.Add(Pontoon);
	}
	SternPontoonIndex = Buoyancy->BuoyancyData.Pontoons.Num() - 1;
	BowPontoonIndex = 0;
}

void ARiptideBoat::OnConstruction(const FTransform& Transform)
{
	Super::OnConstruction(Transform);
	ApplyModels();
}

void ARiptideBoat::ApplyModels()
{
	if (UStaticMesh* Hull = HullModel.LoadSynchronous())
	{
		HullMesh->SetStaticMesh(Hull);
		HullMesh->SetRelativeLocation(FVector::ZeroVector);
		HullMesh->SetRelativeScale3D(FVector::OneVector);
	}
	if (UStaticMesh* Outboard = OutboardModel.LoadSynchronous())
	{
		MotorMesh->SetStaticMesh(Outboard);
		MotorMesh->SetRelativeLocation(OutboardPivot);
		MotorMesh->SetRelativeScale3D(FVector::OneVector);
	}
}

void ARiptideBoat::BeginPlay()
{
	ApplyModels();

	// Size buoyancy to the hull's mass before the buoyancy component starts (it begins play inside Super).
	// The engine spreads one pontoon's worth of lift across all pontoons (their coefficients sum to 1),
	// so lift = submerged volume of one pontoon * BuoyancyCoefficient. Pick the coefficient that holds the
	// boat up with the pontoons PontoonRestDepth under (a spherical cap), which puts the waterline at WaterlineZ.
	{
		const float R = PontoonRadius;
		const float D = PontoonRestDepth;
		const float RestVolumeCm3 = (UE_PI / 3.f) * D * D * (3.f * R - D);
		const float WeightUnreal = HullMassKg * FMath::Abs(GetWorld()->GetGravityZ());
		Buoyancy->BuoyancyData.BuoyancyCoefficient = WeightUnreal / RestVolumeCm3;
		// The engine clamps each pontoon's force; leave room for a fully buried pontoon's full reserve.
		Buoyancy->BuoyancyData.MaxBuoyantForce = WeightUnreal * 20.f;
	}

	Super::BeginPlay();

	HullBody->SetMassOverrideInKg(NAME_None, HullMassKg, true);
	if (HasAuthority())
	{
		FuelLiters = FuelCapacityLiters;
	}

	// The wake foam and sounds are cosmetic, so every machine runs its own for each boat.
	RegisterWithWakeSimulation();
	StartSounds();
	StartWakeFoam();
}

void ARiptideBoat::StartWakeFoam()
{
	if (!FApp::CanEverRender())
	{
		return;
	}
	WakeFoam->SetMaterial(0, WakeFoamMaterial.LoadSynchronous());
	if (AWaterBodyOcean* Ocean = Cast<AWaterBodyOcean>(UGameplayStatics::GetActorOfClass(this, AWaterBodyOcean::StaticClass())))
	{
		WakeFoam->SetWaterBody(Ocean->GetWaterBodyComponent());
	}

	// Churned water from the prop: a wide band that spreads and lingers.
	URiptideWakeFoamComponent::FTrailStyle Churn;
	Churn.StartHalfWidth = HullExtent.Y * 0.8f;
	Churn.GrowthPerSecond = 65.f;
	Churn.LifeSeconds = 9.f;
	Churn.Opacity = 0.7f;
	Churn.WobbleAtBirth = 5.f;
	Churn.WobbleWhenOld = 40.f;
	Churn.WobbleWavelength = 1200.f;
	Churn.WidthVariation = 0.3f;
	Churn.Patchiness = 0.35f;
	SternFoamTrail = WakeFoam->AddTrail(Churn);

	BowSpraySystem.LoadSynchronous();
}

void ARiptideBoat::UpdateWakeFoam(float DeltaSeconds)
{
	if (SternFoamTrail == INDEX_NONE)
	{
		return;
	}

	const FTransform& Xf = HullBody->GetComponentTransform();
	const FVector Right = FVector::VectorPlaneProject(Xf.GetUnitAxis(EAxis::Y), FVector::UpVector).GetSafeNormal();
	const bool bInWater = Buoyancy && Buoyancy->IsInWaterBody();
	const float Speed01 = bInWater ? FMath::Clamp(GetSpeedKnots() / FoamFullSpeedKnots, 0.f, 1.f) : 0.f;

	// Prop churn: from moving through the water, and from the prop turning even at low speed. It builds quickly
	// but dies away slowly, so the prop lifting clear on a swell for a moment thins the trail instead of breaking it.
	const float ChurnTarget = IsPropellerSubmerged() ? FMath::Max(Speed01, 0.35f * FMath::Abs(EngineOutput)) : 0.f;
	ChurnLevel = FMath::FInterpTo(ChurnLevel, ChurnTarget, DeltaSeconds, ChurnTarget > ChurnLevel ? 8.f : 1.f);
	WakeFoam->UpdateTrail(SternFoamTrail, DeltaSeconds, Xf.TransformPosition(FVector(-HullExtent.X, 0.f, WaterlineZ)), Right, ChurnLevel);

	// The wake's V (the bow waves and their foam) comes from the wake simulation, so only the prop's churn is
	// laid here.
	WakeFoam->RebuildMesh();
}

void ARiptideBoat::SprayAtBow(float Strength)
{
	UNiagaraSystem* Spray = BowSpraySystem.Get();
	if (!Spray || !FApp::CanEverRender())
	{
		return;
	}
	// Thrown forward and up off the bow, bigger for a harder hit.
	const FTransform& Xf = HullBody->GetComponentTransform();
	// Starts just ahead of the stem at the waterline, so it bursts out of the water rather than the deck.
	const FVector Bow = Xf.TransformPosition(FVector(HullExtent.X + 30.f, 0.f, WaterlineZ));
	const FRotator Up = FRotator(55.f, GetActorRotation().Yaw, 0.f);
	UNiagaraFunctionLibrary::SpawnSystemAtLocation(this, Spray, Bow, Up, FVector(FMath::Lerp(2.f, 3.5f, Strength)));
}

AActor* ARiptideBoat::SpawnWakeSimulation(UClass* SimClass)
{
	// Each machine runs its own simulation around its own player, so it's created locally rather than placed
	// in the level. It renders into textures, so machines that can't render (dedicated servers, headless test
	// runs) skip it; its setup divides by the render size and crashes without a renderer.
	if (!FApp::CanEverRender())
	{
		return nullptr;
	}
	AActor* Ocean = UGameplayStatics::GetActorOfClass(this, AWaterBodyOcean::StaticClass());
	if (!Ocean)
	{
		return nullptr;
	}

	// Settings go in before the Blueprint's construction script runs, which sizes its render targets from them.
	AActor* Sim = GetWorld()->SpawnActorDeferred<AActor>(SimClass, FTransform(GetActorLocation()));
	if (!Sim)
	{
		return nullptr;
	}
	auto Set = [Sim](const TCHAR* Name, TFunctionRef<void(FProperty*, void*)> Apply)
	{
		if (FProperty* Prop = Sim->GetClass()->FindPropertyByName(Name))
		{
			Apply(Prop, Prop->ContainerPtrToValuePtr<void>(Sim));
		}
		else
		{
			UE_LOG(LogRiptideBoat, Warning, TEXT("Wake simulation has no '%s' setting"), Name);
		}
	};
	Set(TEXT("WaterBody"), [Ocean](FProperty* P, void* V) { if (FObjectPropertyBase* O = CastField<FObjectPropertyBase>(P)) { O->SetObjectPropertyValue(V, Ocean); } });
	Set(TEXT("Follow Player "), [](FProperty* P, void* V) { if (FBoolProperty* B = CastField<FBoolProperty>(P)) { B->SetPropertyValue(V, true); } });  // trailing space is in the Blueprint's name
	Set(TEXT("Simulation World Size"), [this](FProperty* P, void* V) { if (FNumericProperty* N = CastField<FNumericProperty>(P)) { N->SetFloatingPointPropertyValue(V, WakeSimulationSize); } });
	Set(TEXT("Damping"), [this](FProperty* P, void* V) { if (FNumericProperty* N = CastField<FNumericProperty>(P)) { N->SetFloatingPointPropertyValue(V, WakeSimulationDamping); } });
	Set(TEXT("Travel Speed"), [this](FProperty* P, void* V) { if (FNumericProperty* N = CastField<FNumericProperty>(P)) { N->SetFloatingPointPropertyValue(V, WakeSimulationWaveSpeed); } });
	Sim->FinishSpawning(FTransform(GetActorLocation()));
	return Sim;
}

void ARiptideBoat::StartSounds()
{
	if (GetNetMode() == NM_DedicatedServer)
	{
		return;
	}

	// Other boats fade out over 150 m; at the helm (within 5 m of the motor) it's full volume.
	SoundFalloff = NewObject<USoundAttenuation>(this);
	FSoundAttenuationSettings& Falloff = SoundFalloff->Attenuation;
	Falloff.bAttenuate = true;
	Falloff.bSpatialize = true;
	Falloff.AttenuationShape = EAttenuationShape::Sphere;
	Falloff.AttenuationShapeExtents = FVector(500.f, 0.f, 0.f);
	Falloff.FalloffDistance = 15000.f;

	EngineAudio->AttenuationSettings = SoundFalloff;
	EngineHighAudio->AttenuationSettings = SoundFalloff;
	WashAudio->AttenuationSettings = SoundFalloff;
	EngineAudio->SetSound(EngineSound.LoadSynchronous());
	EngineHighAudio->SetSound(EngineHighSound.LoadSynchronous());
	WashAudio->SetSound(WashSound.LoadSynchronous());
	WashAudio->SetVolumeMultiplier(0.f);
	WashAudio->Play();
	for (const TSoftObjectPtr<USoundBase>& Slap : HullSlapSounds)
	{
		Slap.LoadSynchronous();
	}
}

void ARiptideBoat::UpdateSounds(float DeltaSeconds)
{
	if (!SoundFalloff)
	{
		return;
	}

	// Engine: runs while it has fuel and isn't dead. Pitch and volume follow the actual engine output (so a
	// sputter is heard as a dip), and it races when the prop leaves the water and loses its load.
	const bool bRunning = FuelLiters > 0.f && EngineHealth > 0.f;
	if (bRunning != bEngineSoundRunning)
	{
		bEngineSoundRunning = bRunning;
		for (UAudioComponent* Layer : { EngineAudio.Get(), EngineHighAudio.Get() })
		{
			if (bRunning)
			{
				Layer->FadeIn(0.5f);
			}
			else
			{
				Layer->FadeOut(1.5f, 0.f);
			}
		}
	}
	const float Output = FMath::Abs(EngineOutput);
	const float TargetRevs = FMath::Min(1.f, Output * (IsPropellerSubmerged() ? 1.f : 1.f + PropOutOverRev));
	EngineRevs = FMath::FInterpTo(EngineRevs, TargetRevs, DeltaSeconds, 6.f);

	// Engine speed moves between idle and full on a musical (log) scale. Each recording is pitched to that speed,
	// and the two crossfade at equal power by where the speed sits between them.
	const float Hz = EngineIdleHz * FMath::Pow(EngineFullHz / EngineIdleHz, EngineRevs);
	const float HighWeight = FMath::Clamp(
		FMath::Loge(Hz / EngineLowRecordingHz) / FMath::Loge(EngineHighRecordingHz / EngineLowRecordingHz), 0.f, 1.f);
	const float Volume = FMath::Lerp(EngineIdleVolume, 1.f, Output);
	EngineAudio->SetPitchMultiplier(Hz / EngineLowRecordingHz);
	EngineHighAudio->SetPitchMultiplier(Hz / EngineHighRecordingHz);
	EngineAudio->SetVolumeMultiplier(Volume * FMath::Max(0.f, FMath::Cos(HighWeight * UE_HALF_PI)));
	EngineHighAudio->SetVolumeMultiplier(Volume * FMath::Max(0.f, FMath::Sin(HighWeight * UE_HALF_PI)));

	// Wash: water rushing past the hull, rising with speed. Silent out of the water.
	const bool bInWater = Buoyancy && Buoyancy->IsInWaterBody();
	const float SpeedFraction = bInWater ? FMath::Clamp(GetSpeedKnots() / WashFullSpeedKnots, 0.f, 1.f) : 0.f;
	WashAudio->SetVolumeMultiplier(FMath::Pow(SpeedFraction, 1.5f));
	WashAudio->SetPitchMultiplier(FMath::Lerp(0.85f, 1.15f, SpeedFraction));

	// Hull slap: the bow dropping into the water (or a wave rising into it) fast enough, near the surface.
	// Louder the harder it hits.
	// Measured only between two frames spent in the water: before that the bow's water reading isn't valid.
	const float Freeboard = GetBowFreeboardCm();
	const bool bHadFreeboard = bHaveBowFreeboard;
	const float ClosingSpeed = bHadFreeboard ? (PrevBowFreeboard - Freeboard) / FMath::Max(DeltaSeconds, 1e-3f) : 0.f;
	PrevBowFreeboard = Freeboard;
	bHaveBowFreeboard = bInWater;
	SlapCooldownLeft -= DeltaSeconds;
	if (bHadFreeboard && bInWater && SlapCooldownLeft <= 0.f && ClosingSpeed > SlapMinSpeed && Freeboard < 25.f && HullSlapSounds.Num() > 0)
	{
		const float Strength = FMath::Clamp((ClosingSpeed - SlapMinSpeed) / (SlapFullSpeed - SlapMinSpeed), 0.f, 1.f);
		const float SlapVolume = FMath::Lerp(0.25f, 1.f, Strength);
		if (USoundBase* Slap = HullSlapSounds[FMath::RandRange(0, HullSlapSounds.Num() - 1)].Get())
		{
			const FVector Bow = HullBody->GetComponentTransform().TransformPosition(FVector(HullExtent.X * 0.8f, 0.f, WaterlineZ));
			UGameplayStatics::PlaySoundAtLocation(this, Slap, Bow, SlapVolume, FMath::FRandRange(0.9f, 1.1f), 0.f, SoundFalloff);
		}
		SprayAtBow(Strength);
		SlapCooldownLeft = SlapCooldown;
		UE_LOG(LogRiptideBoat, Verbose, TEXT("Hull slap at %.0f cm/s, volume %.2f"), ClosingSpeed, SlapVolume);
	}
}

void ARiptideBoat::RegisterWithWakeSimulation()
{
	// The Water plugin's fluid simulation (BP_FluidSim_01) ripples the water surface around the local player.
	// It's a Blueprint, so its "Register Dynamic Force" function and FluidForceDynamic struct are reached
	// through reflection, matching the struct's fields by their name prefix.
	static const TCHAR* SimClassPath = TEXT("/Water/FluidSimulation/Blueprints/BP_FluidSim_01.BP_FluidSim_01_C");
	UClass* SimClass = LoadClass<AActor>(nullptr, SimClassPath);
	if (!SimClass)
	{
		return;
	}
	AActor* Sim = UGameplayStatics::GetActorOfClass(this, SimClass);
	if (!Sim)
	{
		Sim = SpawnWakeSimulation(SimClass);
	}
	if (!Sim)
	{
		return;
	}

	UFunction* Register = Sim->FindFunction(TEXT("Register Dynamic Force"));
	if (!Register)
	{
		UE_LOG(LogTemp, Warning, TEXT("Riptide: wake simulation has no 'Register Dynamic Force'; no wake for %s"), *GetName());
		return;
	}

	auto SetNumber = [](FProperty* Prop, void* Container, double Value)
	{
		if (FNumericProperty* Num = CastField<FNumericProperty>(Prop))
		{
			void* Ptr = Num->ContainerPtrToValuePtr<void>(Container);
			if (Num->IsFloatingPoint())
			{
				Num->SetFloatingPointPropertyValue(Ptr, Value);
			}
		}
	};
	auto SetObject = [](FProperty* Prop, void* Container, UObject* Value)
	{
		if (FObjectPropertyBase* Obj = CastField<FObjectPropertyBase>(Prop))
		{
			Obj->SetObjectPropertyValue(Obj->ContainerPtrToValuePtr<void>(Container), Value);
		}
	};

	FStructOnScope Params(Register);
	uint8* ParamMemory = Params.GetStructMemory();
	bool bFilledForce = false;
	for (TFieldIterator<FProperty> It(Register); It && It->HasAnyPropertyFlags(CPF_Parm); ++It)
	{
		FProperty* Param = *It;
		const FString ParamName = Param->GetName();
		if (FStructProperty* ForceParam = CastField<FStructProperty>(Param))
		{
			void* Force = ForceParam->ContainerPtrToValuePtr<void>(ParamMemory);
			for (TFieldIterator<FProperty> Field(ForceParam->Struct); Field; ++Field)
			{
				const FString FieldName = Field->GetName();
				if (FieldName.StartsWith(TEXT("ForceRadius")))
				{
					SetNumber(*Field, Force, WakeRadius);
				}
				else if (FieldName.StartsWith(TEXT("ForceComponent")))
				{
					SetObject(*Field, Force, WakeSource);
					bFilledForce = true;
				}
				else if (FieldName.StartsWith(TEXT("MaterialOverride")))
				{
					SetObject(*Field, Force, WakeForceMaterial.LoadSynchronous());
				}
			}
		}
		else if (ParamName.StartsWith(TEXT("Tracked")))
		{
			SetObject(Param, ParamMemory, WakeSource);
		}
		else if (ParamName.StartsWith(TEXT("WaterLevel")))
		{
			// Sea level. The test maps put the ocean surface at Z = 0.
			SetNumber(Param, ParamMemory, 0.0);
		}
	}

	if (!bFilledForce)
	{
		UE_LOG(LogTemp, Warning, TEXT("Riptide: wake simulation's force struct didn't match; no wake for %s"), *GetName());
		return;
	}
	Sim->ProcessEvent(Register, ParamMemory);
	UE_LOG(LogTemp, Log, TEXT("Riptide: %s registered with the wake simulation"), *GetName());
}

void ARiptideBoat::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);

	DOREPLIFETIME(ARiptideBoat, ThrottleLever);
	DOREPLIFETIME(ARiptideBoat, EngineOutput);
	DOREPLIFETIME(ARiptideBoat, SteerAngleDeg);
	DOREPLIFETIME(ARiptideBoat, FuelLiters);
	DOREPLIFETIME(ARiptideBoat, EngineHealth);
}

// --- Input ---

void ARiptideBoat::BuildInput()
{
	if (HelmMapping)
	{
		return;
	}

	// Built in code so the project runs without any input assets authored in the editor.
	ThrottleAction = NewObject<UInputAction>(this, TEXT("IA_Throttle"));
	ThrottleAction->ValueType = EInputActionValueType::Axis1D;

	SteerAction = NewObject<UInputAction>(this, TEXT("IA_Steer"));
	SteerAction->ValueType = EInputActionValueType::Axis1D;

	CutThrottleAction = NewObject<UInputAction>(this, TEXT("IA_CutThrottle"));
	CutThrottleAction->ValueType = EInputActionValueType::Boolean;

	LookAction = NewObject<UInputAction>(this, TEXT("IA_Look"));
	LookAction->ValueType = EInputActionValueType::Axis2D;

	HelmMapping = NewObject<UInputMappingContext>(this, TEXT("IMC_Helm"));

	HelmMapping->MapKey(ThrottleAction, EKeys::W);
	FEnhancedActionKeyMapping& ThrottleDown = HelmMapping->MapKey(ThrottleAction, EKeys::S);
	ThrottleDown.Modifiers.Add(NewObject<UInputModifierNegate>(HelmMapping));

	HelmMapping->MapKey(SteerAction, EKeys::D);
	FEnhancedActionKeyMapping& SteerLeft = HelmMapping->MapKey(SteerAction, EKeys::A);
	SteerLeft.Modifiers.Add(NewObject<UInputModifierNegate>(HelmMapping));

	HelmMapping->MapKey(CutThrottleAction, EKeys::X);
	HelmMapping->MapKey(LookAction, EKeys::Mouse2D);

	// Gamepad: right trigger / left trigger for throttle, left stick to steer, right stick to look.
	HelmMapping->MapKey(ThrottleAction, EKeys::Gamepad_RightTriggerAxis);
	FEnhancedActionKeyMapping& PadReverse = HelmMapping->MapKey(ThrottleAction, EKeys::Gamepad_LeftTriggerAxis);
	PadReverse.Modifiers.Add(NewObject<UInputModifierNegate>(HelmMapping));
	HelmMapping->MapKey(SteerAction, EKeys::Gamepad_LeftX);
	HelmMapping->MapKey(CutThrottleAction, EKeys::Gamepad_FaceButton_Right);
	HelmMapping->MapKey(LookAction, EKeys::Gamepad_Right2D);
}

void ARiptideBoat::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

	BuildInput();

	if (const APlayerController* PC = Cast<APlayerController>(GetController()))
	{
		if (UEnhancedInputLocalPlayerSubsystem* Subsystem =
				ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PC->GetLocalPlayer()))
		{
			Subsystem->AddMappingContext(HelmMapping, 0);
		}
	}

	if (UEnhancedInputComponent* Input = Cast<UEnhancedInputComponent>(PlayerInputComponent))
	{
		Input->BindAction(ThrottleAction, ETriggerEvent::Triggered, this, &ARiptideBoat::OnThrottle);
		Input->BindAction(ThrottleAction, ETriggerEvent::Completed, this, &ARiptideBoat::OnThrottleReleased);
		Input->BindAction(SteerAction, ETriggerEvent::Triggered, this, &ARiptideBoat::OnSteer);
		Input->BindAction(SteerAction, ETriggerEvent::Completed, this, &ARiptideBoat::OnSteerReleased);
		Input->BindAction(CutThrottleAction, ETriggerEvent::Started, this, &ARiptideBoat::OnCutThrottle);
		Input->BindAction(LookAction, ETriggerEvent::Triggered, this, &ARiptideBoat::OnLook);
	}
}

void ARiptideBoat::OnThrottle(const FInputActionValue& Value)
{
	ThrottleInput = FMath::Clamp(Value.Get<float>(), -1.f, 1.f);
}

void ARiptideBoat::OnThrottleReleased(const FInputActionValue& Value)
{
	ThrottleInput = 0.f;
}

void ARiptideBoat::OnSteer(const FInputActionValue& Value)
{
	SteerInput = FMath::Clamp(Value.Get<float>(), -1.f, 1.f);
}

void ARiptideBoat::OnSteerReleased(const FInputActionValue& Value)
{
	SteerInput = 0.f;
}

void ARiptideBoat::OnCutThrottle(const FInputActionValue& Value)
{
	bCutThrottleRequested = true;
}

void ARiptideBoat::OnLook(const FInputActionValue& Value)
{
	const FVector2D Delta = Value.Get<FVector2D>();
	LookYaw = FMath::Clamp(LookYaw + Delta.X * LookSensitivity, -170.f, 170.f);
	LookPitch = FMath::Clamp(LookPitch + Delta.Y * LookSensitivity, -70.f, 70.f);
	HelmCamera->SetRelativeRotation(FRotator(LookPitch, LookYaw, 0.f));
}

void ARiptideBoat::ServerSetControls_Implementation(float InThrottleInput, float InSteerInput, bool bInCutThrottle)
{
	ThrottleInput = FMath::Clamp(InThrottleInput, -1.f, 1.f);
	SteerInput = FMath::Clamp(InSteerInput, -1.f, 1.f);
	bCutThrottleRequested |= bInCutThrottle;
}

// --- Simulation ---

void ARiptideBoat::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	if (IsLocallyControlled() && !HasAuthority())
	{
		ServerSetControls(ThrottleInput, SteerInput, bCutThrottleRequested);
		bCutThrottleRequested = false;
	}

	if (HasAuthority())
	{
		UpdateControls(DeltaSeconds);
		UpdateEngine(DeltaSeconds);
		ApplyThrust();
		ApplyHydrodynamics();
	}

	// The outboard swings on its bracket as it steers (the thrust turns the same way in ApplyThrust).
	if (OutboardModel.IsValid())
	{
		MotorMesh->SetRelativeRotation(FRotator(0.f, -SteerAngleDeg, 0.f));
	}

	UpdateSounds(DeltaSeconds);
	UpdateWakeFoam(DeltaSeconds);

	if (IsLocallyControlled())
	{
		DrawDebugHud();
	}
}

void ARiptideBoat::UpdateControls(float DeltaSeconds)
{
	if (bCutThrottleRequested)
	{
		ThrottleLever = 0.f;
		bCutThrottleRequested = false;
	}

	// The lever moves while the key is held and stays put when released, like a real throttle.
	ThrottleLever = FMath::Clamp(ThrottleLever + ThrottleInput * ThrottleLeverRate * DeltaSeconds, -1.f, 1.f);

	// The motor swings back to centre when the wheel is let go.
	const float TargetSteer = SteerInput * MaxSteerAngleDeg;
	SteerAngleDeg = FMath::FInterpConstantTo(SteerAngleDeg, TargetSteer, DeltaSeconds, SteerRateDeg);
}

void ARiptideBoat::UpdateEngine(float DeltaSeconds)
{
	float Target = ThrottleLever;

	if (FuelLiters <= 0.f || EngineHealth <= 0.f)
	{
		Target = 0.f;
	}
	else if (EngineHealth < 0.5f)
	{
		// A damaged engine cuts out at random, more often the worse it is.
		if (SputterTimeLeft > 0.f)
		{
			SputterTimeLeft -= DeltaSeconds;
			Target = 0.f;
		}
		else if (FMath::FRand() < (0.5f - EngineHealth) * 2.f * DeltaSeconds)
		{
			SputterTimeLeft = FMath::FRandRange(0.3f, 1.5f);
		}
	}

	EngineOutput = FMath::FInterpTo(EngineOutput, Target, DeltaSeconds, EngineSpoolRate);
	FuelLiters = FMath::Max(0.f, FuelLiters - FMath::Abs(EngineOutput) * FuelBurnPerSecond * DeltaSeconds);
}

bool ARiptideBoat::IsPropellerSubmerged() const
{
	if (!Buoyancy || !Buoyancy->IsInWaterBody() || !Buoyancy->BuoyancyData.Pontoons.IsValidIndex(SternPontoonIndex))
	{
		return false;
	}

	// Compare the prop with the water surface at the stern directly. The stern pontoon itself can sit
	// clear of the water while the prop, which hangs lower, is still under.
	const FSphericalPontoon& Stern = Buoyancy->BuoyancyData.Pontoons[SternPontoonIndex];
	return Propeller->GetComponentLocation().Z < Stern.WaterHeight;
}

void ARiptideBoat::ApplyThrust()
{
	if (FMath::IsNearlyZero(EngineOutput, 0.001f) || !IsPropellerSubmerged())
	{
		return;
	}

	const float Scale = EngineOutput > 0.f ? 1.f : ReverseThrustScale;
	const float ThrustN = MaxThrust * EngineOutput * Scale;

	// Steering right swings the prop so it pushes the stern left, which turns the bow right.
	const FVector Up = HullBody->GetUpVector();
	const FVector ThrustDir = HullBody->GetForwardVector().RotateAngleAxis(-SteerAngleDeg, Up);

	HullBody->AddForceAtLocation(ThrustDir * ThrustN * NewtonsToUnreal, Propeller->GetComponentLocation());
}

void ARiptideBoat::ApplyHydrodynamics()
{
	if (!Buoyancy || !Buoyancy->IsInWaterBody())
	{
		return;
	}

	// Quadratic water drag in the hull's frame: slippery going forward, stubborn going sideways.
	const FTransform& Xf = HullBody->GetComponentTransform();
	const FVector LocalVelMs = Xf.InverseTransformVectorNoScale(HullBody->GetPhysicsLinearVelocity()) / 100.f;

	const FVector LocalDragN(
		-ForwardDrag * LocalVelMs.X * FMath::Abs(LocalVelMs.X),
		-LateralDrag * LocalVelMs.Y * FMath::Abs(LocalVelMs.Y),
		-HeaveDamping * LocalVelMs.Z);

	HullBody->AddForce(Xf.TransformVectorNoScale(LocalDragN) * NewtonsToUnreal);

	// Planing lift: water striking the forward hull bottom pushes up ahead of the centre of mass,
	// so the bow trims up with speed. Only going forward, and capped so crests don't launch the boat.
	// It only exists where the hull is in the water: scaled by how deep the forward bottom sits compared
	// with its resting draft, so a bow lifting clear (or leaving a crest) loses the lift and settles back.
	if (LocalVelMs.X > 0.f)
	{
		const FVector LiftPoint = Xf.TransformPosition(FVector(HullExtent.X * 0.3f, 0.f, -HullExtent.Z));

		float WaterHeightSum = 0.f;
		int32 NumForward = 0;
		for (const FSphericalPontoon& Pontoon : Buoyancy->BuoyancyData.Pontoons)
		{
			if (Pontoon.RelativeLocation.X > 0.f)
			{
				WaterHeightSum += Pontoon.WaterHeight;
				++NumForward;
			}
		}
		const float RestDraft = WaterlineZ + HullExtent.Z;
		const float Wetness = NumForward > 0
			? FMath::Clamp((WaterHeightSum / NumForward - LiftPoint.Z) / RestDraft, 0.f, 1.f)
			: 0.f;

		const float WeightN = HullMassKg * FMath::Abs(GetWorld()->GetGravityZ()) / 100.f;
		const float LiftN = Wetness * FMath::Min(PlaningLift * LocalVelMs.X * LocalVelMs.X, WeightN * MaxPlaningLiftFraction);
		HullBody->AddForceAtLocation(Xf.GetUnitAxis(EAxis::Z) * LiftN * NewtonsToUnreal, LiftPoint);
	}

	// Resist spinning in place, and resist rocking so the hull settles after a wave instead of building up a roll.
	const FVector Up = HullBody->GetUpVector();
	const FVector AngVel = HullBody->GetPhysicsAngularVelocityInRadians();
	const float YawRate = FVector::DotProduct(AngVel, Up);
	const FVector RockRate = AngVel - Up * YawRate;
	HullBody->AddTorqueInRadians(-Up * YawRate * YawDamping - RockRate * RockDamping, NAME_None, true);
}

float ARiptideBoat::GetBowFreeboardCm() const
{
	if (!Buoyancy || !Buoyancy->BuoyancyData.Pontoons.IsValidIndex(BowPontoonIndex))
	{
		return 0.f;
	}
	const FSphericalPontoon& Bow = Buoyancy->BuoyancyData.Pontoons[BowPontoonIndex];
	const FVector BowDeckEdge = HullBody->GetComponentTransform().TransformPosition(FVector(HullExtent.X, 0.f, HullExtent.Z));
	return BowDeckEdge.Z - Bow.WaterHeight;
}

float ARiptideBoat::GetSpeedKnots() const
{
	return HullBody->GetComponentVelocity().Size() * CmPerSecToKnots;
}

void ARiptideBoat::ApplyEngineDamage(float Amount)
{
	if (HasAuthority())
	{
		EngineHealth = FMath::Clamp(EngineHealth - Amount, 0.f, 1.f);
	}
}

void ARiptideBoat::SetHelmInput(float Throttle, float Steer)
{
	if (HasAuthority())
	{
		ThrottleInput = FMath::Clamp(Throttle, -1.f, 1.f);
		SteerInput = FMath::Clamp(Steer, -1.f, 1.f);
	}
}

void ARiptideBoat::DrawDebugHud() const
{
	if (!GEngine)
	{
		return;
	}

	// Temporary readout for tuning the handling; replaced by real gauges later.
	const uint64 KeyBase = 0x52495054ull;
	GEngine->AddOnScreenDebugMessage(KeyBase + 0, 0.f, FColor::White,
		FString::Printf(TEXT("Speed %.1f kn   Throttle %+.0f%%   Engine %+.0f%%"),
			GetSpeedKnots(), ThrottleLever * 100.f, EngineOutput * 100.f));
	GEngine->AddOnScreenDebugMessage(KeyBase + 1, 0.f, FColor::White,
		FString::Printf(TEXT("Motor %+.0f deg   Fuel %.1f L   Engine health %.0f%%"),
			SteerAngleDeg, FuelLiters, EngineHealth * 100.f));
	GEngine->AddOnScreenDebugMessage(KeyBase + 2, 0.f, IsPropellerSubmerged() ? FColor::Green : FColor::Red,
		IsPropellerSubmerged() ? TEXT("Prop in water") : TEXT("Prop out of water"));
}
