"""Riptide's coconut palms, generated in code like the boat. Plain Python, no Unreal.

A palm here is built the way a real coconut palm (Cocos nucifera) grows:
- a slim grey trunk, swollen at the foot, that leans from the ground and sweeps back up toward the light, ringed
  with old leaf scars;
- a crown of 20-odd fronds, each 4-5 m long: a stiff midrib that arches under its own weight, carrying about 35
  pairs of narrow leaflets, each one its own folded blade that droops toward its tip. The youngest fronds stand
  near upright in the middle, the mature ones arch out and down, the oldest hang below the crown, and a few dead
  brown ones hang against the trunk;
- clusters of coconuts under the crown.

Nothing is a flat card with a picture on it: from underneath, against the sky, you see through between the
leaflets, as you do under a real palm.

Each frond is placed by the plant's real spiral (each new frond about 137.5 degrees round from the last) with
seeded scatter on every angle, length and droop, so no two fronds or palms match and no pattern shows.

Axes are Unreal's (X forward, Y right, Z up), in metres here and centimetres in the file; a palm's lean is toward
+X. Materials: PalmTrunk, PalmCrown (the fibrous leaf bases), PalmStem (midribs), PalmFrond (green leaflets;
u counts 0-1 across the blade plus a whole number 0-3 choosing a shade of green, v runs base to tip),
PalmFrondDry (dead leaflets), Coconut.
"""
import math
import random


def _add(a, b): return (a[0] + b[0], a[1] + b[1], a[2] + b[2])
def _sub(a, b): return (a[0] - b[0], a[1] - b[1], a[2] - b[2])
def _mul(a, k): return (a[0] * k, a[1] * k, a[2] * k)
def _dot(a, b): return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
def _cross(a, b): return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def _norm(a):
    length = math.sqrt(_dot(a, a))
    return (a[0] / length, a[1] / length, a[2] / length) if length > 1e-9 else (0.0, 0.0, 1.0)


def _rotate(v, axis, angle):
    """v turned about a unit axis by an angle in radians."""
    c, s = math.cos(angle), math.sin(angle)
    return _add(_add(_mul(v, c), _mul(_cross(axis, v), s)), _mul(axis, _dot(axis, v) * (1.0 - c)))


class Mesh:
    def __init__(self):
        self.verts = []     # (position, normal, uv)
        self.faces = {}     # material -> [(i, j, k)]

    def vert(self, p, n, uv):
        self.verts.append((p, n, uv))
        return len(self.verts) - 1

    def tri(self, material, a, b, c):
        self.faces.setdefault(material, []).append((a, b, c))

    def quad(self, material, a, b, c, d):
        self.tri(material, a, b, c)
        self.tri(material, a, c, d)

    def tube(self, material, points, radii, sides, v_per_metre=1.0, u_repeat=1.0, cap_end=True):
        """A tube along a list of points with a radius at each: smooth sides, its far end closed to a point."""
        rings = []
        length = 0.0
        side = None
        for i, p in enumerate(points):
            ahead = points[min(i + 1, len(points) - 1)]
            behind = points[max(i - 1, 0)]
            tangent = _norm(_sub(ahead, behind))
            if side is None:
                side = _norm(_cross(tangent, (0.0, 1.0, 0.0) if abs(tangent[1]) < 0.9 else (1.0, 0.0, 0.0)))
            # Carried along the tube, so it never twists.
            side = _norm(_sub(side, _mul(tangent, _dot(side, tangent))))
            other = _cross(tangent, side)
            if i:
                length += math.sqrt(_dot(_sub(p, points[i - 1]), _sub(p, points[i - 1])))
            ring = []
            for k in range(sides + 1):
                a = 2.0 * math.pi * k / sides
                out = _add(_mul(side, math.cos(a)), _mul(other, math.sin(a)))
                ring.append(self.vert(_add(p, _mul(out, radii[i])), out, (u_repeat * k / sides, length * v_per_metre)))
            rings.append(ring)
        for i in range(len(rings) - 1):
            for k in range(sides):
                self.quad(material, rings[i][k], rings[i][k + 1], rings[i + 1][k + 1], rings[i + 1][k])
        if cap_end:
            tip_dir = _norm(_sub(points[-1], points[-2]))
            tip = self.vert(_add(points[-1], _mul(tip_dir, radii[-1] * 0.8)), tip_dir, (0.5, length * v_per_metre))
            for k in range(sides):
                self.tri(material, rings[-1][k], rings[-1][k + 1], tip)

    def write_obj(self, path, comment="Riptide palm, generated by riptide_palm_mesh.py"):
        """OBJ for Unreal's importer, which keeps X and Z and flips Y: positions and normals go out as (X, -Y, Z) in
        centimetres, and every triangle is wound to face the way its normals point."""
        def out(v):
            return (v[0], -v[1], v[2])
        with open(path, "w") as f:
            f.write("# %s\n" % comment)
            for p, n, uv in self.verts:
                f.write("v %.2f %.2f %.2f\n" % out(_mul(p, 100.0)))
            for p, n, uv in self.verts:
                f.write("vn %.4f %.4f %.4f\n" % out(n))
            for p, n, uv in self.verts:
                f.write("vt %.4f %.4f\n" % uv)
            for material, faces in self.faces.items():
                f.write("usemtl %s\n" % material)
                for a, b, c in faces:
                    pa, pb, pc = out(self.verts[a][0]), out(self.verts[b][0]), out(self.verts[c][0])
                    face = _cross(_sub(pb, pa), _sub(pc, pa))
                    want = _add(_add(out(self.verts[a][1]), out(self.verts[b][1])), out(self.verts[c][1]))
                    if _dot(face, want) < 0.0:
                        b, c = c, b
                    a1, b1, c1 = a + 1, b + 1, c + 1
                    f.write("f %d/%d/%d %d/%d/%d %d/%d/%d\n" % (a1, a1, a1, b1, b1, b1, c1, c1, c1))

    def triangle_count(self):
        return sum(len(faces) for faces in self.faces.values())


# --- Parts -------------------------------------------------------------------------------------------------------

def _trunk(mesh, rng, height, lean, bole):
    """The trunk's centre line and radii. It leaves the ground leaning and sweeps upright; returns the point and
    direction at its top, where the crown sits."""
    steps = max(24, int(height / 0.14))
    wander = rng.uniform(-0.25, 0.25) * lean
    points, radii = [], []
    for i in range(steps + 1):
        t = i / steps
        z = -0.35 + (height + 0.35) * t                         # starts below ground, so it stands on a slope
        sweep = 1.0 - (1.0 - t) ** 2.3
        x = lean * sweep
        y = wander * math.sin(math.pi * t) * 0.6
        points.append((x, y, z))
        up = max(z, 0.0)
        # Swollen at the foot, slim above, a little thicker again under the crown; each leaf scar a slight ridge.
        radius = 0.15 + (bole - 0.15) * math.exp(-up / 0.5) + 0.02 * max(0.0, (t - 0.9) / 0.1)
        radius *= 1.0 + 0.035 * math.sin(up * 2.0 * math.pi / 0.28)
        radii.append(radius)
    mesh.tube("PalmTrunk", points, radii, 14, v_per_metre=1.0 / 0.9, u_repeat=1.0, cap_end=False)
    top = points[-1]
    direction = _norm(_sub(points[-1], points[-3]))
    return top, direction, radii[-1]


def _frond(mesh, rng, base, start, side, length, droop, dry=False, closed=0.0, age=0.5):
    """One frond: `start` is the way its midrib leaves the crown, `side` a unit vector across it (the plane its
    leaflets spread in). `droop` is how far it arches over its length, radians. `closed` 0..1 folds the leaflets
    up along the midrib, as on a frond that hasn't opened yet."""
    steps = 14
    stem_material = "PalmStem" if not dry else "PalmFrondDry"
    leaf_material = "PalmFrond" if not dry else "PalmFrondDry"
    shade = rng.randrange(4)
    sag = rng.uniform(-0.12, 0.12)                              # a slight sideways curve
    twist = rng.uniform(-0.25, 0.25)                            # the whole blade rolled a little about its midrib

    # The midrib: integrate along it, arching toward the ground further out.
    points, tangents, sides = [], [], []
    p, t, s = base, _norm(start), _norm(side)
    seg = length / steps
    for i in range(steps + 1):
        points.append(p)
        tangents.append(t)
        sides.append(s)
        f = (i + 0.5) / steps
        bend = droop * 1.6 * (f ** 1.4) / steps
        axis = _norm(_cross(t, (0.0, 0.0, 1.0))) if abs(t[2]) < 0.999 else s
        t = _norm(_rotate(t, axis, -bend if t[2] > -0.999 else 0.0))
        t = _norm(_rotate(t, (0.0, 0.0, 1.0), sag / steps))
        s = _norm(_sub(s, _mul(t, _dot(s, t))))
        s = _rotate(s, t, twist / steps)
        p = _add(p, _mul(t, seg))
    radii = [0.034 * (1.0 - 0.82 * (i / steps)) + 0.004 for i in range(steps + 1)]
    mesh.tube(stem_material, points, radii, 5, v_per_metre=1.0, u_repeat=1.0)

    # Leaflets, in pairs, from a fifth of the way out to the tip.
    pairs = 42 if not dry else 24
    for j in range(pairs):
        along = 0.2 + 0.8 * (j + rng.uniform(0.15, 0.85)) / pairs
        at = along * steps
        i = min(int(at), steps - 1)
        f = at - i
        origin = _add(_mul(points[i], 1.0 - f), _mul(points[i + 1], f))
        tangent = _norm(_add(_mul(tangents[i], 1.0 - f), _mul(tangents[i + 1], f)))
        across = _norm(_add(_mul(sides[i], 1.0 - f), _mul(sides[i + 1], f)))
        up = _norm(_cross(across, tangent))
        if up[2] < 0.0 and abs(tangent[2]) < 0.95:
            up = _mul(up, -1.0)
        # Longest a little short of half way out, short at both ends.
        reach = math.sin(math.pi * min(1.0, 0.12 + along * 0.95)) ** 0.75
        for hand in (-1.0, 1.0):
            size = (0.42 + 0.68 * reach) * rng.uniform(0.88, 1.1) * (length / 4.6)
            if dry:
                size *= 0.7
            forward = math.radians(rng.uniform(28.0, 40.0) + 30.0 * along ** 2) + closed * math.radians(40.0)
            lift = math.radians(rng.uniform(4.0, 16.0)) * (1.0 - closed * 0.5)
            out = _norm(_add(_add(_mul(across, hand * math.cos(forward)), _mul(tangent, math.sin(forward))), _mul(up, math.sin(lift))))
            width = rng.uniform(0.042, 0.056) * (0.75 + 0.25 * reach) * (0.5 if dry else 1.0)
            # Leaflets on older fronds hang more: the frond becomes a drooping curtain either side of its midrib.
            hang = rng.uniform(0.8, 1.25) * (2.0 if dry else 0.75 + 1.1 * min(age, 1.0))
            _leaflet(mesh, rng, leaf_material, _add(origin, _mul(up, 0.012)), out, tangent, size, width, hang, shade)


def _leaflet(mesh, rng, material, base, out, rib, length, width, hang, shade):
    """One leaflet: a narrow blade folded along its middle, widest a third of the way out, drooping to a point."""
    segments = 3
    rows = []
    p, direction = base, out
    step = length / segments
    for k in range(segments + 1):
        t = k / segments
        across = _norm(_cross(direction, (0.0, 0.0, 1.0))) if abs(direction[2]) < 0.98 else _norm(_cross(direction, rib))
        normal = _norm(_cross(across, direction))
        if normal[2] < 0.0:
            normal = _mul(normal, -1.0)
        half = width * (0.55 + 1.6 * t) * (1.0 - t) ** 0.8 if t > 0.0 else width * 0.5
        half = max(half, 0.0015)
        fold = half * 0.45                                       # edges stand above the midrib: a shallow V
        left = _add(_add(p, _mul(across, -half)), _mul(normal, fold))
        right = _add(_add(p, _mul(across, half)), _mul(normal, fold))
        rows.append((mesh.vert(left, _norm(_add(normal, _mul(across, 0.5))), (shade + 0.0, t)),
                     mesh.vert(p, normal, (shade + 0.5, t)),
                     mesh.vert(right, _norm(_add(normal, _mul(across, -0.5))), (shade + 1.0 - 1e-3, t))))
        # It bends toward the ground more and more toward its tip.
        if abs(direction[2]) < 0.98:
            axis = _norm(_cross(direction, (0.0, 0.0, 1.0)))
            direction = _norm(_rotate(direction, axis, -hang * 0.4 * (0.4 + 1.2 * t)))
        p = _add(p, _mul(direction, step))
    for k in range(segments):
        a, b = rows[k], rows[k + 1]
        mesh.quad(material, a[0], a[1], b[1], b[0])
        mesh.quad(material, a[1], a[2], b[2], b[1])


def _nut(mesh, centre, rx, rz, tilt):
    rings, sides = 6, 9
    grid = []
    for i in range(rings + 1):
        lat = math.pi * i / rings
        row = []
        for k in range(sides + 1):
            lon = 2.0 * math.pi * k / sides
            n = (math.sin(lat) * math.cos(lon), math.sin(lat) * math.sin(lon), math.cos(lat))
            # A little pointed at the bottom, like a nut in its husk.
            point = (n[0] * rx, n[1] * rx, n[2] * rz * (1.0 + 0.18 * max(0.0, -n[2])))
            point = _rotate(point, (0.0, 1.0, 0.0), tilt)
            row.append(mesh.vert(_add(centre, point), _rotate(n, (0.0, 1.0, 0.0), tilt), (k / sides, i / rings)))
        grid.append(row)
    for i in range(rings):
        for k in range(sides):
            mesh.quad("Coconut", grid[i][k], grid[i][k + 1], grid[i + 1][k + 1], grid[i + 1][k])


# --- A whole palm --------------------------------------------------------------------------------------------------

def build_palm(seed, height, lean, fronds=22, frond_length=4.6, nuts=7, bole=0.3):
    rng = random.Random(seed)
    mesh = Mesh()
    top, axis, top_radius = _trunk(mesh, rng, height, lean, bole)

    # The crown shaft: the fibrous bases of the leaves, a short swelling the fronds grow out of.
    shaft = [_add(top, _mul(axis, d)) for d in (-0.05, 0.12, 0.3, 0.48, 0.62)]
    mesh.tube("PalmCrown", shaft, [top_radius * 1.02, top_radius * 1.3, top_radius * 1.35, top_radius * 1.05, top_radius * 0.5], 12,
              v_per_metre=2.0, u_repeat=2.0)
    heart = _add(top, _mul(axis, 0.42))

    ref = _norm(_cross(axis, (0.0, 1.0, 0.0)))
    turn = rng.uniform(0.0, math.tau)
    dead = rng.randint(2, 4)
    total = fronds + dead
    for i in range(total):
        # Youngest first. Each one 137.5 degrees round from the last, as the plant grows them, with scatter.
        age = i / max(1, fronds - 1)
        angle = turn + i * math.radians(137.5) + rng.uniform(-0.3, 0.3)
        around = _rotate(ref, axis, angle)
        is_dead = i >= fronds
        if is_dead:
            from_up = math.radians(rng.uniform(140.0, 162.0))
            droop = math.radians(rng.uniform(8.0, 20.0))
            length = frond_length * rng.uniform(0.7, 0.9)
        else:
            from_up = math.radians(6.0 + 112.0 * age ** 1.15 + rng.uniform(-8.0, 8.0))
            droop = math.radians(rng.uniform(40.0, 66.0)) * (0.35 + 0.65 * min(1.0, age * 1.6))
            length = frond_length * rng.uniform(0.86, 1.08) * (0.62 + 0.38 * min(1.0, age * 2.2))
        start = _norm(_add(_mul(axis, math.cos(from_up)), _mul(around, math.sin(from_up))))
        side = _norm(_cross(start, axis)) if abs(_dot(start, axis)) < 0.995 else _norm(_cross(axis, around))
        # Older fronds leave the shaft lower down.
        base = _add(heart, _add(_mul(axis, 0.16 - 0.3 * min(age, 1.2)), _mul(around, top_radius * 0.7)))
        _frond(mesh, rng, base, start, side, length, droop, dry=is_dead, closed=max(0.0, 1.0 - age * 6.0) if not is_dead else 0.0,
               age=1.0 if is_dead else age)

    # Coconuts, in two or three bunches tucked under the crown.
    bunches = min(3, max(1, nuts // 3)) if nuts else 0
    left = nuts
    for b in range(bunches):
        angle = turn + b * math.tau / bunches + rng.uniform(-0.5, 0.5)
        around = _rotate(ref, axis, angle)
        count = left if b == bunches - 1 else max(1, nuts // bunches)
        left -= count
        for n in range(count):
            spread = _rotate(around, axis, rng.uniform(-0.5, 0.5))
            centre = _add(_add(top, _mul(axis, 0.02 - 0.16 * (n % 3) + rng.uniform(-0.05, 0.05))),
                          _mul(spread, top_radius + 0.16 + 0.05 * (n // 3)))
            _nut(mesh, centre, rng.uniform(0.1, 0.125), rng.uniform(0.13, 0.155), rng.uniform(-0.4, 0.4))
    return mesh


# The palms the islands plant: (name, arguments). Lean is toward +X: turn the palm to lean it where you want.
PALMS = {
    "SM_Palm_Tall": dict(seed=11, height=11.0, lean=1.1, fronds=30, frond_length=5.4, nuts=8),
    "SM_Palm_Leaning": dict(seed=23, height=9.0, lean=3.2, fronds=28, frond_length=5.2, nuts=6),
    "SM_Palm_Sweeping": dict(seed=37, height=7.6, lean=4.8, fronds=27, frond_length=5.0, nuts=5),
    "SM_Palm_Medium": dict(seed=41, height=7.0, lean=1.4, fronds=28, frond_length=5.0, nuts=7),
    "SM_Palm_Young": dict(seed=53, height=3.6, lean=0.5, fronds=20, frond_length=3.9, nuts=0, bole=0.26),
}


def write_palms(out_dir):
    """Writes every palm's OBJ into out_dir. Returns [(name, path, triangles)]."""
    import os
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for name, args in PALMS.items():
        mesh = build_palm(**args)
        path = os.path.join(out_dir, name + ".obj")
        mesh.write_obj(path)
        written.append((name, path, mesh.triangle_count()))
    return written


if __name__ == "__main__":
    import sys
    for name, path, tris in write_palms(sys.argv[1]):
        print(name, tris, "triangles")
