"""Turns a designed island (riptide_island_shape.py) into ground meshes for Unreal: 64 m squares of terrain, land
and seabed in one continuous surface. Plain Python, no Unreal.

The squares near the coast and on land have a point every metre; further out to sea, where nobody walks, every
2 m and then every 4 m. Where a fine square meets a coarser one, the fine square's edge is laid along the coarse
one's, so there are no gaps to see through or fall through.

Unreal's axes: X north, Y east, Z up, in centimetres, with the island's centre at the origin and sea level at 0.
"""
import math
import os

CHUNK = 64.0            # metres
FINE, MID, COARSE = 1.0, 2.0, 4.0


def chunk_layout(island):
    """{(cx, cy): cell size} for every 64 m square of the island's patch. (cx, cy) count squares from the
    patch's south-west corner."""
    n = int(round(2 * island.extent / CHUNK))
    layout = {}
    for cy in range(n):
        for cx in range(n):
            x0, y0 = cx * CHUNK - island.extent, cy * CHUNK - island.extent
            nearest, land = 1e9, False
            for iy in range(9):
                for ix in range(9):
                    d = island.coast_distance(x0 + ix * CHUNK / 8.0, y0 + iy * CHUNK / 8.0)
                    land |= d > 0.0
                    nearest = min(nearest, abs(d))
            layout[(cx, cy)] = FINE if (land or nearest < 40.0) else MID if nearest < 150.0 else COARSE
    return layout


def build_chunk(island, layout, key):
    """One square's mesh: (vertices, normals, uvs, triangles), vertices in Unreal centimetres."""
    cx, cy = key
    cell = layout[key]
    n = int(round(CHUNK / cell))
    x0, y0 = cx * CHUNK - island.extent, cy * CHUNK - island.extent

    # Heights on the square's grid plus one point beyond each edge, for slopes that agree with the neighbours'.
    heights = [[island.height(x0 + (ix - 1) * cell, y0 + (iy - 1) * cell) for ix in range(n + 3)] for iy in range(n + 3)]

    def edge_height(x, y, along_x, coarse):
        # On an edge shared with a coarser square, the ground follows that square's straight edge.
        if along_x:
            a = math.floor((x - x0) / coarse) * coarse + x0
            t = (x - a) / coarse
            return island.height(a, y) if t < 1e-6 else island.height(a, y) * (1 - t) + island.height(a + coarse, y) * t
        a = math.floor((y - y0) / coarse) * coarse + y0
        t = (y - a) / coarse
        return island.height(x, a) if t < 1e-6 else island.height(x, a) * (1 - t) + island.height(x, a + coarse) * t

    for side, (ox, oy) in (("s", (0, -1)), ("n", (0, 1)), ("w", (-1, 0)), ("e", (1, 0))):
        coarse = layout.get((cx + ox, cy + oy), cell)
        if coarse <= cell:
            continue
        for i in range(n + 1):
            if side in ("s", "n"):
                iy = 0 if side == "s" else n
                heights[iy + 1][i + 1] = edge_height(x0 + i * cell, y0 + iy * cell, True, coarse)
            else:
                ix = 0 if side == "w" else n
                heights[i + 1][ix + 1] = edge_height(x0 + ix * cell, y0 + i * cell, False, coarse)

    verts, normals, uvs = [], [], []
    for iy in range(n + 1):
        for ix in range(n + 1):
            x, y, h = x0 + ix * cell, y0 + iy * cell, heights[iy + 1][ix + 1]
            dx = (heights[iy + 1][ix + 2] - heights[iy + 1][ix]) / (2 * cell)
            dy = (heights[iy + 2][ix + 1] - heights[iy][ix + 1]) / (2 * cell)
            length = math.sqrt(dx * dx + dy * dy + 1.0)
            # Unreal: X north (the design's y), Y east (the design's x).
            verts.append((y * 100.0, x * 100.0, h * 100.0))
            normals.append((-dy / length, -dx / length, 1.0 / length))
            uvs.append((x, y))
    tris = []
    row = n + 1
    for iy in range(n):
        for ix in range(n):
            a, b, c, d = iy * row + ix, iy * row + ix + 1, (iy + 1) * row + ix, (iy + 1) * row + ix + 1
            # Split each square along the diagonal that bends least, so ridges and gullies stay crisp.
            if abs(heights[iy + 1][ix + 1] - heights[iy + 2][ix + 2]) <= abs(heights[iy + 1][ix + 2] - heights[iy + 2][ix + 1]):
                tris += [(a, d, b), (a, c, d)]
            else:
                tris += [(a, c, b), (b, c, d)]
    return verts, normals, uvs, tris


def write_obj(path, mesh, material="Terrain"):
    """OBJ for Unreal's importer, which keeps X and Z and flips Y: written as (X, -Y, Z), every triangle wound to
    face up."""
    verts, normals, uvs, tris = mesh
    with open(path, "w") as f:
        f.write("# Riptide island terrain, generated by riptide_island_mesh.py\n")
        for x, y, z in verts:
            f.write("v %.2f %.2f %.2f\n" % (x, -y, z))
        for x, y, z in normals:
            f.write("vn %.4f %.4f %.4f\n" % (x, -y, z))
        for u, v in uvs:
            f.write("vt %.3f %.3f\n" % (u, v))
        f.write("usemtl %s\n" % material)
        for a, b, c in tris:
            # Counter-clockwise seen from above in the file's own (right-handed) axes.
            ax, ay = verts[a][0], -verts[a][1]
            bx, by = verts[b][0], -verts[b][1]
            cx, cy = verts[c][0], -verts[c][1]
            if (bx - ax) * (cy - ay) - (by - ay) * (cx - ax) < 0.0:
                b, c = c, b
            a, b, c = a + 1, b + 1, c + 1
            f.write("f %d/%d/%d %d/%d/%d %d/%d/%d\n" % (a, a, a, b, b, b, c, c, c))


def chunk_name(island, key):
    return "SM_%s_%02d_%02d" % (island.name, key[0], key[1])


def write_island(island, out_dir):
    """Writes every square's OBJ into out_dir. Returns [(name, path, cell size)]."""
    os.makedirs(out_dir, exist_ok=True)
    layout = chunk_layout(island)
    written = []
    for key in sorted(layout):
        name = chunk_name(island, key)
        path = os.path.join(out_dir, name + ".obj")
        write_obj(path, build_chunk(island, layout, key))
        written.append((name, path, layout[key]))
    return written


if __name__ == "__main__":
    import sys
    import time
    import riptide_island_shape as shape
    start = time.time()
    isl = shape.StartCay()
    files = write_island(isl, sys.argv[1])
    sizes = {}
    for _, _, cell in files:
        sizes[cell] = sizes.get(cell, 0) + 1
    print(len(files), "squares", sizes, "in %.0f s" % (time.time() - start))
